### ISSUE TITLE
Mute clients not muting them from admin chat/asay

### ISSUE THREAD

**Issue by pittm8** [TeamUlysses/ulx#100]
### Steps to reproduce
1.mute client
2. Use asay whilst muted
3.bingo!

### Expected behavior
Muting players should prevent them from using chat at all including admin chat.

### Actual behavior
Mutes player from chat but always them to use asay still.

**Comment by Nayruden** [comment]
We intentionally left this open, they should be able to communicate with someone, somehow. If they are abusing, recommend kicking/banning.
