### ISSUE TITLE
Problem with grenades

### ISSUE THREAD

**Issue by Heqsu** [TeamUlysses/ulx#102]
Hello. I have a small problem with grenades, because if we want to throw it, it stays where we are and stays in the air, exploding. Do you know what I can do?

//SERVER GMOD

**Comment by Nayruden** [comment]
What does this have to do with ULX?

**Comment by Heqsu** [comment]
Because I have no idea if this is possible with this?

**Comment by Nayruden** [comment]
ULX doesn't modify grenade behavior.
