### ISSUE TITLE
time tracker glitch

### ISSUE THREAD

**Issue by BadGamer042** [TeamUlysses/ulx#104]
on a server the time tracker is stuck at 9 hours so whenever I play it goes up but when I log back in it's reset  to 9 hours pls help me

**Comment by Nayruden** [comment]
Is this the case for all other players on the server as well?

**Comment by Nayruden** [comment]
What is the time tracker you are talking about? I had assumed UTime, but you're reporting this on the ULX repository.

**Comment by Nayruden** [comment]
No response from OP, closing issue.
