### ISSUE TITLE
Teleport trace is skewed

### ISSUE THREAD

**Issue by adosikas** [TeamUlysses/ulx#108]
The trace used for ulx teleport isn't consistent with the eye angle, as the endpos isn't shifted, while the startpos is. This leads to a slight, but annoying offset in expected teleport target.

Code in question: https://github.com/TeamUlysses/ulx/blob/master/lua/ulx/modules/sh/teleport.lua#L290-L291

I think it would make sense to make the offset half the player height (or whatever fraction is required for traceEntity to work properly), and apply it to both startpos and endpos, instead of hardcoding it to 32 on starpos and 0 on endpos. This would also allow it working correctly with rescaled players.

**Comment by Nayruden** [comment]
Thank you for your input! Your suggestion combined with http://wiki.garrysmod.com/page/Entity/DropToFloor may do the trick.

**Comment by zpetty33** [comment]
Trace for teleport reworked. Using Player:GetEyeTrace now which takes all of this into consideration internally. Works great!
