### ISSUE TITLE
Garrys mod Darkrp Error

### ISSUE THREAD

**Issue by scream55555** [TeamUlysses/ulx#111]
### Steps to reproduce
1.start Garry's mod Darkrp server
2.Join server
3.Look in console

### Expected behavior
In console I get Nothing

### Actual behavior
Tell us what happens instead I see an error pop up

### Error(s) in player's console, if any
[ERROR] addons/ulx/lua/ulx/xgui/settings/server.lua:1024: attempt to index field 'server_name' (a nil value)
### Version
Run "ulx version" in console and paste the result
ULX version: v3.73d (03/21/17)

**Comment by Codingale** [comment]
It's something to do with fonts being nil. Have you tried a clean reinstall of ULX & ULib by deleting the data folders etc?

**Comment by zpetty33** [comment]
This issue was likely caused by clientside errors or corrupt files.
