### ISSUE TITLE
ULX Bring teleports them behind me?

### ISSUE THREAD

**Issue by PNCamben** [TeamUlysses/ulx#112]
### Steps to reproduce
1.
2.  !bring *anyone*
3.

### Expected behavior
The player will be brought in front of where the admin is.

### Actual behavior
The person teleports behind the admin.

### Error(s) in server console, if any
None
### Error(s) in player's console, if any
None
### Version
 ULib v2.60  
ULX v3.70

## Sorry if this isn't even a bug, it just got annoying dealing with sits when they kept teleporting behind me rather than infront of me. ##

**Comment by Nayruden** [comment]
This is the intended behavior.
