### ISSUE TITLE
attempt to index a string value with bad key ('CodeEnt' is not part of the string library)

### ISSUE THREAD

**Issue by plagued911** [TeamUlysses/ulx#114]
When I run my GMOD server, i get this error from VCMOD:
[ERROR] addons/vcmod_main_autoupdate/lua/weapons/vc_spikestrip_wep/shared.lua:33: attempt to index a string value with bad key ('CodeEnt' is not part of the string library)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:297
    3. unknown - addons/vcmod_main_autoupdate/lua/weapons/vc_spikestrip_wep/shared.lua:33

[ERROR] addons/vcmod_main_autoupdate/lua/weapons/vc_wrench/shared.lua:28: attempt to index a string value with bad key ('CodeEnt' is not part of the string library)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:297
    3. unknown - addons/vcmod_main_autoupdate/lua/weapons/vc_wrench/shared.lua:28

**Comment by Nayruden** [comment]
What does this have to do with ULX?
