### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by ZlayYTKA** [TeamUlysses/ulx#116]
### Steps to reproduce
1. Translate ulx at addons\ulx-v3_73\lua\ulx\modules\sh   chat.lua
2. Join server
3. See a error

### Expected behavior
When i just translate ulx at Russian, and there was all translated!

### Actual behavior
After translating ulx there was an error, and the tab 'Chat'

### Error(s) in server console, if any
[ERROR] bad argument #1 to ULib.cmds.TranslateCommand:defaultAccess (string expected)
  1. error - [C]:-1
   2. checkArg - addons/[r] ulib-v2_63/lua/ulib/shared/misc.lua:585
    3. defaultAccess - addons/[r] ulib-v2_63/lua/ulib/shared/commands.lua:1220
     4. unknown - addons/[r] ulx-v3_73/lua/ulx/modules/sh/chat.lua:9
      5. include - [C]:-1
       6. unknown - addons/[r] ulx-v3_73/lua/ulx/cl_init.lua:17
        7. include - [C]:-1
         8. unknown - addons/[r] ulx-v3_73/lua/ulib/modules/ulx_init.lua:4
          9. include - [C]:-1
           10. unknown - addons/[r] ulib-v2_63/lua/ulib/cl_init.lua:24
            11. include - [C]:-1
             12. unknown - addons/[r] ulib-v2_63/lua/autorun/ulib_init.lua:5
### Error(s) in player's console, if any
Nothing, but when you turn on the !menu, there is no 'Chat' button
### Version
ULib v2.63
ULX v3.73

**Comment by Nayruden** [comment]
You'll need to share your translated version of sh_chat.lua for us to
determine what the cause of your error is.

**Comment by ZlayYTKA** [comment]
I get my own command
function ulx.serverinfo()
    chat.AddText(Color(155,200,111), "[INFO]", Color( 100, 255, 100 ), "Приветствуем, вы на сервере ********!\n Создатель данного сервера - ЗлойANIME\n У нашего сервера есть своя группа в вк - vk.com/**********")
end
local serverinfo = ulx.command( CATEGORY_NAME, "ulx serverinfo", ulx.serverinfo, "!info" )
serverinfo:defaultAccess( ULib.ACCESS_USER )
serverinfo:help( "Отобразить инфу." )

And here is my translate
[github.zip](https://github.com/TeamUlysses/ulx/files/1450420/github.zip)

**Comment by ZlayYTKA** [comment]
I found the problem
