### ISSUE TITLE
Support double quote in luarun

### ISSUE THREAD

**Issue by h3xcat** [TeamUlysses/ulx#119]
This been driving me insane for years, please add double quote support. I bet it's not only me that had an issue with this.
```
] ulx luarun ="a"
Result: nil
(SILENT) You ran lua: tmp_var= a
] ulx luarun ='a'
(SILENT) You ran lua: tmp_var='a '
Result: a 
```

**Comment by end360** [comment]
pretty sure its a problem with the way console handles double quotes.

**Comment by zpetty33** [comment]
Correct. The console strips out double quotes and packages the contents as a string string internally. Using single quotes is the way to go for this kind of thing. Sorry!
