### ISSUE TITLE
ULX Ban Message

### ISSUE THREAD

**Issue by deinemudda32** [TeamUlysses/ulx#12]
Looks really ugly at the current state and it could provide more information.

Should be added:
You are banned from this server!
* Reason: reason or unknown
* Admin: name or console
* You were banned on: os.date
* You will be unbanned in: Never or os.date

**Comment by Nayruden** [comment]
How would you suggest fixing being ugly?

**Comment by deinemudda32** [comment]
Remove the "disconnect:" from the message would help a lot.

**Comment by Nayruden** [comment]
Unfortunately, we can't do that without using a source module (like
GateKeeper, if that's even still around). Any other suggestions for
improving the look and feel?

Information displayed is something we knew people would want to change when
we created this. We are happy with what we currently show for the default.
Not everyone will want to display additional information. We may make it
configurable in the future.

**Comment by deinemudda32** [comment]
https://scriptfodder.com/scripts/view/248
This addon removed it.
Maybe ask the author of it, how they did do it.

**Comment by Nayruden** [comment]
That's the connection message -- ULX doesn't show "disconnected" in that
state either. It's only when they are already connected and you are kicking
them that "Disconnected" has to be shown in the way Garry has it setup
currently.

**Comment by Nayruden** [comment]
Alternatively, I suppose ULX could work around the engine limitation by
forcing the user to reconnect in order to show the message without the
"disconnect", but that is way too hackish for my tastes.

**Comment by deinemudda32** [comment]
I should've known that.

**Comment by Nayruden** [comment]
Any other suggestions for improving look and feel?

**Comment by deinemudda32** [comment]
Maybe leave a few empy lines. So there is more structure.

**Comment by deinemudda32** [comment]
I dont know honestly.
For the informations about which admin did ban you and when did you get banned etc., you could add a convar like "ulx_showdetailedbans". Just in case.

Maybe you can change the message if you are banned from the server while being on it, to the old message.

**Comment by Nayruden** [comment]
You like the old message format more than the new one?

**Comment by deinemudda32** [comment]
I didnt mean that.

I meant if you get the "disconnect" thing, maybe display the old style, because of that.

**Comment by comedinha** [comment]
The hook CheckPassword with check if player is ban and return false, playermsg

**Comment by Nayruden** [comment]
Bruno, what are you talking about? ULX is using that hook -- do you know of
a better way?

**Comment by comedinha** [comment]
Change the reason to most details

Not tested:
```
local banJoinMsg = [[
===========YOU ARE BANNED===========
By: %s
Reason: %s
Ban since: %s
Time Left: %s]]
local function checkBan( steamid64, ip, password, clpassword, name )
	local steamid = util.SteamIDFrom64( steamid64 )
	local banData = ULib.bans[ steamid ]
	if not banData then return end -- Not banned

	local admin = "Console"
	if banData.admin and banData.admin ~= "" then
		admin = banData.admin
	end
	
	local reason = "(None given)"
	if banData.reason and banData.reason ~= "" then
		reason = banData.reason
	end

	local timeban = "Unknown"
	if banData.time > 0 then
		timeban = os.date("%d/%m/%y %H:%M", timeban.time)
	end

	local unbanStr = nil
	local unban = tonumber( banData.unban )
	if unban and unban > 0 then
		unbanStr = ULib.secondsToStringTime( unban - os.time() )
	end

	if reason or unbanStr then -- Only give this message if we have something useful to display
		Msg(string.format("%s (%s)<%s> was kicked by ULib because they are on the ban list\n", name, steamid, ip))
		return false, banJoinMsg:format( admin, reason, timeban, unbanStr or "(Permaban)" )
	end
end
hook.Add( "CheckPassword", "ULibBanCheck", checkBan, HOOK_LOW )
```

**Comment by comedinha** [comment]
And on addBan not now ========YOU HAVE BEEN BANNED========
