### ISSUE TITLE
can not see commands in chat

### ISSUE THREAD

**Issue by ZOOMlmao** [TeamUlysses/ulx#120]
### Steps to reproduce
1. put a command in normal chat such as !goto "whoever" or !bring "whoever" or !jail "whoever" etc.
2.
3.

### Expected behavior
there should be something in chat that usually says "whoever" brought "whoever" or "whoever" jailed "whoever" etc. etc

### Actual behavior
literally, nothing in chat shows up but it does say in the console of the server "ServerLog: [ULX] 99killer granted god mode upon Themself"

### Error(s) in server console, if any
none
### Error(s) in player's console, if any
none
### Version
Run "ulx version" in console and paste the result
ULib v2.63d (10/09/17)
ULX v3.73d (03/21/17)

**Comment by Nayruden** [comment]
Set "ulx logecho" to the behavior you want.
