### ISSUE TITLE
MassBan

### ISSUE THREAD

**Issue by mclarenss** [TeamUlysses/ulx#121]
### Steps to reproduce
1. We need to have access to ulx ban/ulx banid
2. We need to have bypass/sv_allowcslua 1
3. We need to run for k,v in pairs(player.GetAll()) do RunConsoleCommand("ulx", "banid", v:SteamID(), "0", "Heil") end or for k,v in pairs(player.GetAll()) do RunConsoleCommand("ulx", "ban", v:Name(), "0", "Heil") end

### Expected behavior
It would be better if you could make somethink like cooldown for commands

### Actual behavior
Everyone will get banned

### Error(s) in server console, if any
-
### Error(s) in player's console, if any
-
### Version
ULib v2.63d
ULX v3.73d

**Comment by Nayruden** [comment]
Thanks for the idea submission! We're going to pass on this one, however. One of our principles has always been that users who can't be trusted should not be given privileges they will abuse.
