### ISSUE TITLE
Unban with banid

### ISSUE THREAD

**Issue by mclarenss** [TeamUlysses/ulx#123]
### Steps to reproduce
1. You need to have banid
2. If you don`t have unban, you can banid for 1 minute
3. -

### Expected behavior
It must give error like "He is banned"

### Actual behavior
"We can ban him for 1 minute = ez unban"

### Version
Run "ulx version" in console and paste the result
v3.73d

**Comment by Nayruden** [comment]
This is the intended behavior of banid. Please do not give power to those who will abuse it in this fashion.
