### ISSUE TITLE
Game Freeze by map change (only if ULX is in collection)

### ISSUE THREAD

**Issue by Agaros007** [TeamUlysses/ulx#127]
### Steps to reproduce
1.sorry, i downt know, 2 of the players on my server have this problem, the game freeze in loading screen every map change, the completly uninstall and reinstall, no changes, if i take ULX from the collection no freezes anymore.

https://steamcommunity.com/sharedfiles/filedetails/?id=1244728377 (if you need to know what addons i use)

Gamemode TTT

### Expected behavior
Map should load by players

### Actual behavior
game freeze

### Error(s) in server console, if any
no error in console :( they must kill the process console say they disconnect 

### Error(s) in player's console, if any
cant load because its frozen by mapchange

### Version
ulx version
ULib v2.63w
ULX v3.73w

**Comment by Nayruden** [comment]
Do you still have this issue without the "ULX Remade" addon in your
collection?

**Comment by Agaros007** [comment]
I normaly use ULX, i want to try ULX remade to test if the problem is the same whit this addon ^^

**Comment by zpetty33** [comment]
Closed due to inactivity.
