### ISSUE TITLE
I unbanned multiple users but they're still not able to join the server

### ISSUE THREAD

**Issue by brandonsturgeon** [TeamUlysses/ulx#128]
### Steps to reproduce
1. banid user's steam id
2. unban user
3. ???
4. do not profit

### Expected behavior
The user should be properly unbanned and should be able to join the server

### Actual behavior
The user is not able to join the server and continues to see their (now invalidated) ban message

### Version
no response to `ulx version`

Clearly something is wrong and I don't know how to instruct reproduction..
Really I'm just asking how to troubleshoot this problem, I haven't experienced this problem in the almost 9 years of using ULX. Should I manually pull the sv_db and make sure their ban isn't in there?

I've checked the bans list in the ulx menu and they players aren't in there anymore. Not sure what's going on.

**Comment by Nayruden** [comment]
This isn't the area for help and support. If you're not seeing a reply to `ulx version`, you are running a pretty old version -- please upgrade.

**Comment by brandonsturgeon** [comment]
It was just a permission problem:
```
ULib v2.52d
ULX v3.62d
```
ULX and ULiB are only one minor version behind.

If this isn't the place for support, where is?

**Comment by Nayruden** [comment]
http://forums.ulysessmod.net

**Comment by brandonsturgeon** [comment]
![image](https://user-images.githubusercontent.com/7936439/40273269-184a9b54-5b72-11e8-9baa-a957eb8f24f4.png)

**Comment by brandonsturgeon** [comment]
Ah, thank you :)
