### ISSUE TITLE
Error on banning non existent user(XGUI)

### ISSUE THREAD

**Issue by deinemudda32** [TeamUlysses/ulx#13]
[ERROR] addons/ulx/lua/ulx/xgui/bans.lua:21: Tried to use invalid object (type Panel) (Object was NULL or not of the right type)
  1. GetValue - [C]:-1
   2. DoClick - addons/ulx/lua/ulx/xgui/bans.lua:21
    3. OnMouseReleased - lua/vgui/dlabel.lua:218
     4. unknown - lua/vgui/dmenuoption.lua:116

**Comment by SticklyMan** [comment]
Fixed in https://github.com/TeamUlysses/ulx/commit/4b5d7291e3ffa129c1f73918371f142c54deba2e
