### ISSUE TITLE
Issue with ULib and Climbswep2

### ISSUE THREAD

**Issue by FableChaser** [TeamUlysses/ulx#130]
### Steps to reproduce
1. Load into singleplayer DarkRP with Climbswep2 and Ulib
2. Watch as your console floods with the same error on spawn
3. Cry

### Expected behavior
I load in, use climbswep or do literally anything I want and enjoy life

### Actual behavior
Load in, console floods with exact same error a hundred times over.

### Error(s) in server console, if any
N/A Though I expect it to be the same.

### Error(s) in player's console, if any
File exists in two addons - possible conflicts! lua/ulib/shared/hook.lua (ULib and Climb SWEP 2)

[ERROR] lua/weapons/climb_swep2/init.lua:54: attempt to index field 'ClimbSlideSound' (a nil value)
  1. fn - lua/weapons/climb_swep2/init.lua:54
   2. unknown - lua/ulib/shared/hook.lua:109

### Version
Run "ulx version" in console and paste the result

No idea if this is explicitly ULIB or not. But idk, maybe someone here can at least point me in the right direction. Uninstalling Climbswep is a big no no, so i really just need to know if im fucked or if this is salvageable.

**Comment by Nayruden** [comment]
I know nothing about CimbSWEP, but it looks like it has a file at lua/ulib/shared/hook.lua? Since it's using our path, we can't fix that on our side.
