### ISSUE TITLE
Cant See Groups Tab

### ISSUE THREAD

**Issue by Dylan0302** [TeamUlysses/ulx#131]
### Expected behavior
Tell us what should happen
I made a server and cant take ownership and not do anything

### Actual behavior
Tell us what happens instead
I cant do anything.

### Error(s) in server console, if any
No

### Error(s) in player's console, if any
No
### Version
Run "ulx version" in console and paste the result
ULib v2.63w
ULX v3.73w

**Comment by FarukGamer** [comment]
You might know something called "Console"

Type this.
ulx adduser "<here you name>" "superadmin"
