### ISSUE TITLE
Using 'ulx resettodefaults' omits some configuration files

### ISSUE THREAD

**Issue by Timmy** [TeamUlysses/ulx#132]
### Steps to reproduce
Run `ulx resettodefaults FORCE` from the server console.

### Expected behavior
All ULX and ULib configuration should be purged.

### Actual behavior
Some configuration data is omitted:
- `data/ulx/motd.txt`
- `data/ulx/banmessage.txt`
- Any per-gamemode/per-map configuration files
- Temporary bans in `sv.db`

The command also tries to delete `data/ulib/bans.txt`. This file is already deleted by ULib after it migrates bans to the SQLite database.

### Version
ULib v2.63d (05/12/18)
ULX v3.73d (05/21/18)

**Comment by zpetty33** [comment]
bans in sv.db are now removed appropriately. The remaining files were omitted intentionally. The command is really meant to reset users and groups. For a true reset, deleting the files manually is usually suggested.
