### ISSUE TITLE
My ULX command is appearing as uncategorized.

### ISSUE THREAD

**Issue by lRoberth** [TeamUlysses/ulx#134]
### Steps to reproduce
1. Creating your own ULX CMD
2. Trying to use it using the GUI
3. Only appears as uncategorized

### Expected behavior
Appear on the specified category.

### Actual behavior
Doesn't appear, but the command does work.

### Error(s) in server console, if any
None

### Error(s) in player's console, if any
None

### Version
Run "ulx version" in console and paste the result
ULib v2.63
ULX v3.73

[My code here.](https://pastebin.com/Pg2tiS2H)

**Comment by zpetty33** [comment]
Unable to work this issue with provided information, and linked code is not lua. Age of issue considered, I'm closing the ticket. Open a new one if you are still having the issue
