### ISSUE TITLE
ULX Unauthed Player Errors= Rockmen

### ISSUE THREAD

**Issue by Rhynobyte** [TeamUlysses/ulx#135]
### Steps to reproduce
1.Install ULX Normally
2.Load into Server

### Expected behavior
Load normally no Rock People...

### Actual behavior
When I load into the server ULX give me an Unauthed Player error and turns everyone into rock people...
It is a ULX problem because when I launch the server without it there are no issues.

### Error(s) in server console, if any
[ERROR] addons/ulib-v2_63/lua/ulib/server/ucl.lua:1111: attempt to call upvalue 'playerAuth' (a nil value)
1. fn - addons/ulib-v2_63/lua/ulib/server/ucl.lua:1111
2. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
3. UniqueID - [C]:-1
4. echoToAdmins - addons/ulx-v3_73/lua/ulx/log.lua:164
5. fn - addons/ulx-v3_73/lua/ulx/log.lua:202
6. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
ServerLog: [FAdmin] Rhynobyte (STEAM_0:0:81151341) Spawned for the first time
[ERROR] Unauthed player
1. query - [C]:-1
2. fn - addons/ulx-v3_73/lua/ulx/base.lua:78
3. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
[ERROR] gamemodes/starwarsrp/gamemode/modules/base/sv_gamemode_functions.lua:615: attempt to index local 'jobTable' (a nil value)
1. unknown - gamemodes/starwarsrp/gamemode/modules/base/sv_gamemode_functions.lua:615
[ERROR] addons/ulx-v3_73/lua/ulx/modules/uteam.lua:23: attempt to index a nil value
1. fn - addons/ulx-v3_73/lua/ulx/modules/uteam.lua:23
2. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
[ERROR] Unauthed player
1. query - [C]:-1
2. fn - addons/ulib-v2_63/lua/ulib/shared/cami_ulib.lua:18
3. Call - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
4. PlayerHasAccess - addons/ulib-v2_63/lua/ulib/shared/cami_global.lua:370
5. calculatePlayerPrivilege - gamemodes/starwarsrp/gamemode/modules/fpp/pp/sh_settings.lua:133
6. recalculateCanTouch - gamemodes/starwarsrp/gamemode/modules/fpp/pp/server/ownability.lua:228
7. unknown - gamemodes/starwarsrp/gamemode/modules/fpp/pp/server/core.lua:650
Timer Failed! [FPP_recalculate_cantouch_2][@gamemodes/starwarsrp/gamemode/modules/fpp/pp/server/core.lua (line 649)]
ServerLog: [FAdmin] Rhynobyte (STEAM_0:0:81151341) Got killed by N/A with a N/A
[ERROR] gamemodes/starwarsrp/gamemode/modules/base/sv_gamemode_functions.lua:403: attempt to index local 'jobTable' (a nil value)
1. unknown - gamemodes/starwarsrp/gamemode/modules/base/sv_gamemode_functions.lua:403
[Rhynobyte|2|STEAM_0:0:81151341] Lua Error:
[ERROR] Unauthed player
1. query - [C]:-1
2. refresh - addons/ulx-v3_73/lua/ulx/xgui/commands.lua:302
3. unknown - addons/ulx-v3_73/lua/ulx/xgui/commands.lua:391
4. include - [C]:-1
5. fn - addons/ulx-v3_73/lua/ulx/modules/cl/xgui_client.lua:142
6. Call - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
7. fn - addons/ulib-v2_63/lua/ulib/cl_init.lua:49
8. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
[Rhynobyte|2|STEAM_0:0:81151341] Lua Error:
[ERROR] Unauthed player
1. query - [C]:-1
2. updateVoteMaps - addons/ulx-v3_73/lua/ulx/xgui/maps.lua:88
3. unknown - addons/ulx-v3_73/lua/ulx/xgui/maps.lua:163
4. include - [C]:-1
5. fn - addons/ulx-v3_73/lua/ulx/modules/cl/xgui_client.lua:142
6. Call - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
7. fn - addons/ulib-v2_63/lua/ulib/cl_init.lua:49
8. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
[Rhynobyte|2|STEAM_0:0:81151341] Lua Error:
[ERROR] Unauthed player
1. query - [C]:-1
2. processModules - addons/ulx-v3_73/lua/ulx/modules/cl/xgui_client.lua:235
3. fn - addons/ulx-v3_73/lua/ulx/modules/cl/xgui_client.lua:189
4. Call - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
5. fn - addons/ulib-v2_63/lua/ulib/cl_init.lua:49
6. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
[ERROR] Unauthed player
1. query - [C]:-1
2. sendDataTable - addons/ulx-v3_73/lua/ulx/modules/xgui_server.lua:184
3. unknown - addons/ulx-v3_73/lua/ulx/modules/xgui_server.lua:105
4. unknown - addons/ulx-v3_73/lua/ulx/modules/xgui_server.lua:72
5. unknown - lua/includes/modules/concommand.lua:54
[ERROR] gamemodes/starwarsrp/gamemode/modules/base/sv_gamemode_functions.lua:615: attempt to index local 'jobTable' (a nil value)
1. unknown - gamemodes/starwarsrp/gamemode/modules/base/sv_gamemode_functions.lua:615
2. Spawn - [C]:-1
3. unknown - gamemodes/base/gamemode/player.lua:115
[ERROR] addons/ulx-v3_73/lua/ulx/modules/uteam.lua:23: attempt to index a nil value
1. fn - addons/ulx-v3_73/lua/ulx/modules/uteam.lua:23
2. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
3. Spawn - [C]:-1
4. unknown - gamemodes/base/gamemode/player.lua:115

### Error(s) in player's console, if any
///////////////////////////////////////
//  ULX GUI -- Made by Stickly Man!  //
///////////////////////////////////////
// Loading GUI Modules...            //
//   bans.lua                        //

[ERROR] Unauthed player
  1. query - [C]:-1
   2. refresh - addons/ulx-v3_73/lua/ulx/xgui/commands.lua:302
    3. unknown - addons/ulx-v3_73/lua/ulx/xgui/commands.lua:391
     4. include - [C]:-1
      5. fn - addons/ulx-v3_73/lua/ulx/modules/cl/xgui_client.lua:142
       6. Call - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
        7. fn - addons/ulib-v2_63/lua/ulib/cl_init.lua:49
         8. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109

//   commands.lua                    //
//   groups.lua                      //

[ERROR] Unauthed player
  1. query - [C]:-1
   2. updateVoteMaps - addons/ulx-v3_73/lua/ulx/xgui/maps.lua:88
    3. unknown - addons/ulx-v3_73/lua/ulx/xgui/maps.lua:163
     4. include - [C]:-1
      5. fn - addons/ulx-v3_73/lua/ulx/modules/cl/xgui_client.lua:142
       6. Call - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
        7. fn - addons/ulib-v2_63/lua/ulib/cl_init.lua:49
         8. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109

//   maps.lua                        //
//   settings.lua                    //
// Loading Setting Modules...        //
//   client.lua                      //
//   server.lua                      //
// Loading Gamemode Module(s)...     //
//   sandbox.lua                     //
//   No module found!                //
// Modules Loaded!                   //
///////////////////////////////////////

[ERROR] Unauthed player
  1. query - [C]:-1
   2. processModules - addons/ulx-v3_73/lua/ulx/modules/cl/xgui_client.lua:235
    3. fn - addons/ulx-v3_73/lua/ulx/modules/cl/xgui_client.lua:189
     4. Call - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
      5. fn - addons/ulib-v2_63/lua/ulib/cl_init.lua:49
       6. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109

### Version
Ulx- 3.73
ULib- 2.63

**Comment by FunnyCraft** [comment]
Hello you fixed its?

**Comment by joeyjumper94** [comment]
i did
check the size of garrysmod/data/ulib/groups.txt
if it's bigger than 49KB, consider deleting it and remaking your ulx groups

**Comment by zpetty33** [comment]
This issue is caused by issues in your gamemode causing the gamemode to not fully load up. The player doesn't fully load so it doesn't auth properly causing errors in ULX to throw. This can't be fixed from ULX's position.
