### ISSUE TITLE
XMENU WEONG USAGE

### ISSUE THREAD

**Issue by ImWuX** [TeamUlysses/ulx#138]
### Steps to reproduce
1.open xmenu
2.run any function
3.

### Expected behavior
Execute the function

### Actual behavior
Tells me im using the wrong usage “Usage:”
Happens witht the in game consile commands too

### Error(s) in server console, if any
None

### Error(s) in player's console, if any
“Usage: “

### Version
Run "ulx version" in console and paste the result
ULib v2.63w
ULX v3.73w

**Comment by jellyton69** [comment]
Yeah this issue is starting to get really annoying, I have no idea what the issue is, this just randomly started happening to me.

**Comment by WEEZOOKARP** [comment]
Same issue here it just says the command is using the wrong syntax even when i use the xgui
happens all the time and i can't even add admins without going into the servers console

**Comment by zpetty33** [comment]
@SticklyMan is this still an issue, do you know what's going on here?

**Comment by SticklyMan** [comment]
I don't think I was ever able to reproduce this. Based on conversations in https://github.com/TeamUlysses/ulx/issues/136, it likely was another addon causing some problems (and I suspect other addons were messing with some internal xgui calls). I'll see if I can make it more resilient regardless. I'm going to close out this old issue- if anyone else is experiencing issues, please create a new issue!
