### ISSUE TITLE
Unknown Error(xgui)

### ISSUE THREAD

**Issue by deinemudda32** [TeamUlysses/ulx#14]
[ERROR] addons/ulx/lua/ulx/xgui/commands.lua:316: attempt to call method 'Toggle' (a nil value)
1. unknown - addons/ulx/lua/ulx/xgui/commands.lua:316

Just appeard.

**Comment by Nayruden** [comment]
What were you doing when you got this error?

**Comment by mcNuggets1** [comment]
These sort of Errors do normally happen, when panels are getting invalid, due to closing the panel.

**Comment by SticklyMan** [comment]
Completely unable to reproduce. If it keeps happening, I'll need a lot more info, as it looks to be some kind of race condition with data refreshing (like with permissions changing) while user interacts with the menu. Either that or auto-refreshing while developing third-party ULX commands. Either way, I'm at a loss for now.
