### ISSUE TITLE
Superadmin can't use staff like bring

### ISSUE THREAD

**Issue by momsta060** [TeamUlysses/ulx#140]
### Steps to reproduce
1. Sorry I don't have any steps to reproduce this, this all happened out of nowhere
2.
3.

### Expected behavior
The staff member should be able to use the basic commands as they are set to superadmin.

### Actual behavior
So whenever staff members on my server try using the bring command it says they don't have access to the command, there's no error message in the server command and there's no error message in my staffs game console.

### Version
Run "ulx version" in console and paste the result
ulx version
ULib v2.63d (05/12/18)
ULX v3.73d (05/21/18)

**Comment by Nayruden** [comment]
Sounds like they don't have permission to use the command... closing as this isn't a bug. Even permissions for superadmins are configurable. If you need help configuring permissions, head to the forums at ulyssesmod.net
