### ISSUE TITLE
Superadmin don't have perms for the role.

### ISSUE THREAD

**Issue by momsta060** [TeamUlysses/ulx#141]
### Steps to reproduce
1. There are no step to reproduce this as this has happened out of nowhere. We haven't edited any code for the config of superadmin. This is an actual issue not a configuration mistake.
2.
3.

### Expected behavior
My staff should be able to use commands like ulx bring or ulx goto and just either bring or goto another player.

### Actual behavior
Ulx says the player with superadmin doesn't have access to this command. I am making this issue again because I have not edited the ulx configuration for superadmin, ulx has broke several times on my server for no reason whatsoever, out of nowhere FAdmin came into place and I haven't installed anything like that. I haven't went into xgui and took away any permissions, this has all happened on its own and is why I am making this issue. I would prefer this issue not to be closed. Thank you

### Error(s) in player's console, if any
[ERROR] RunString:1: unexpected symbol near '<'
1. unknown - RunString:0## Version

Run "ulx version" in console and paste the result
ULX Version = ULib v2.63d (05/12/18)
ULib v2.63d (05/12/18)
ULX v3.73d (05/21/18)
ULX v3.73d (05/21/18)

**Comment by momsta060** [comment]
Ulx worked fine yesterday and the day before, I had a bug where the names of users in the group menu had duplicated but a simple restart fixed those. I haven't edited any config files for anything. This has happened out of nowhere and I have downloaded ulx through mod manager on the server panel

**Comment by Nayruden** [comment]
Run "ulx debuginfo" in console and paste the results here.

**Comment by momsta060** [comment]
ULX version: v3.73d (05/21/18)
ULib version: v2.63d (05/12/18)
Gamemode: DarkRP
Map: rp_downtown_tits_v2
Dedicated server: true

Currently connected players:
Nick                            steamid             uid        id lsh


ULib.ucl.users (#=4):
	STEAM_0:1:78148598:
		name	=	twitch.tv/darkwreth
		deny:
		allow:
		group	=	superadmin
	STEAM_0:1:178750618:
		name	=	Knuffelbeertjes
		deny:
		allow:
		group	=	user
	STEAM_0:1:151032680:
		deny:
		allow:
		name	=	Noice boi
		group	=	superadmin
	STEAM_0:1:56962218:
		allow:
		name	=	Monsta
		deny:
		group	=	user


ULib.ucl.groups (#=3):
	user:
		allow:
			1	=	ulx asay
			2	=	ulx blogs
			3	=	ulx cac
			4	=	ulx copyid
			5	=	ulx help
			6	=	ulx motd
			7	=	ulx psay
			8	=	ulx thetime
			9	=	ulx usermanagementhelp
			10	=	ulx version
			11	=	ulx votemap
			12	=	ulx who
	noaccess:
		allow:
		inherit_from	=	user
	superadmin:
		allow:
		inherit_from	=	user


ULib.ucl.authed (#=0):


Garrysmod default file (#=1):
	Users:
		superadmin:
		admin:


Active workshop addons on this server:
rp_downtown_tits_v2              workshop ID 1590239460
More Materials!                  workshop ID 105841291
Hit Numbers                      workshop ID 110871780
Osama Bin Laden Player Model     workshop ID 175002964
Payday 2 NPCs and Player Models  workshop ID 184396116
Pikachu Player Model             workshop ID 541000799
The Deadpool Super Playermodel Pack workshop ID 1389809127
Doge Playermodel                 workshop ID 656834283
Donald Trump Playermodel         workshop ID 722374307
Terrorist Playermodels           workshop ID 208348503
Teletubbies Playermodel          workshop ID 356485444
Tda Shadow Miku Append (v2)      workshop ID 312489252
T. Rex Playermodel               workshop ID 612053603
Lapis Lazuli                     workshop ID 1479761806
Luke Skywalker                   workshop ID 450353431
Darth Vader                      workshop ID 452065494
Snoop Dogg Playermodel           workshop ID 348376962
Slenderman Playermodel           workshop ID 156545974
Security Guard Pack              workshop ID 169011381
Resident Evil 7 - Umbrella Soldier workshop ID 1282277437
Resident Evil - Vector Playermodel workshop ID 220687225
Rainbow Six Siege - Enhanced Blitz [PM, NPC, Ragdoll] workshop ID 1115501949
R6S IQ Night                     workshop ID 882197988
Mr. Meeseeks playermodel         workshop ID 550768935
Moxxi Moon                       workshop ID 337091393
Monkey Playermodel Chimp         workshop ID 549120288
Faith Connors                    workshop ID 271967400
Marvel Pinball Venom Playermodel/Npc workshop ID 517412134
Lucario Playermodel (Pokken Tournament) workshop ID 949538921
Lich King Model and PLAYERMODEL  workshop ID 179134697
Left shark playermodel           workshop ID 391383735
Jurassic Park velociraptor playermodel workshop ID 681801117
James Bond player model          workshop ID 211991280
Insane Black Rock Shooter (Digitrevx) Playermodel and NPC workshop ID 569813346
Agent 47                         workshop ID 157660704
Haus the Plague Doktor           workshop ID 293674909
Halo 4 Ur-Didact Player/Npc      workshop ID 423474482
Halo 3: Elite Ragdoll/Playermodel/NPCs workshop ID 197850685
Ghost Rider Playermodel          workshop ID 313268673
Gabe Newell player models ®      workshop ID 131541202
FBI Pack                         workshop ID 107411755
Improved Stacker                 workshop ID 264467687
M9K Specialties                  workshop ID 144982052
m9kshotguns+                     workshop ID 834520203
M9K Small Arms pack              workshop ID 128093075
M9K Assault Rifles               workshop ID 128089118
m9kpistols+                      workshop ID 639539553
m9k rifles +                     workshop ID 749554285
ulx Physgun Freeze Script        workshop ID 825240170
ULX DarkRP Commands              workshop ID 1146362924
[DarkRP] Chat Adverting System   workshop ID 927194988
ZerosMethLab - Contentpack       workshop ID 1228585060
gScripts Content Pack            workshop ID 778221022
Pickaxe Content                  workshop ID 402596192
gPrinter Assets                  workshop ID 1201714594
Lean Content                     workshop ID 1422252662
SH Safe Zones Content            workshop ID 1130097039
Bitminers 2 - Server Content     workshop ID 877752661
Pack a Punch - Prop              workshop ID 1582096616
Miner Playermodels               workshop ID 1182053993
Blue's ATM - Content             workshop ID 1207666818
The Sit Anywhere Script!         workshop ID 108176967
3D2D Textscreens                 workshop ID 109643223
Vape SWEP                        workshop ID 673698301
M4A4 - Asiimov                   workshop ID 376025465
CS:GO Knives SWEPs               workshop ID 506283460
Blink SWEP                       workshop ID 746615375
SmartSnap                        workshop ID 104815552
Health NPC | Notifications & Menu workshop ID 795233883
Armor NPC | Notifications & Menu workshop ID 809111313
Groove Street Gang PlayerModels  workshop ID 949554190
North Korea Kim Jong Un NPC & Player model workshop ID 667678266
Magic Wand Rewrite               workshop ID 875498456
Precision Tool                   workshop ID 104482086
tStore - Content                 workshop ID 1443126934

Active legacy addons on this server:
!!!cb-lib                       
advdupe2                        
ahud                            
aMenu                            by arie, version 1.6.1 (2016.07.20)
aScoreboard                      by arie, version 1.0.0 (2016.12.02)
AWarn2                           by Mr.President, version 4.3
bitminers2                      
blogs                           
blues-atm                       
blues-decals                    
DarkRP Modification addon        by FPtje, version 1 (00/00/00)
Door Display                     by Dan, version 1.4
ezjobs                          
gprinters                       
itemstore                       
m9k_assault                     
meth                            
perfect_vault                   
permaprops                      
sh_lounge_chatbox               
sh_reports                      
sh_safezones                    
teleport_system                 
ULib                             by Team Ulysses, version 2.63d (00/00/00)
ULX                              by Team Ulysses, version 3.73d (00/00/00)
unisec                          
wiremod

**Comment by momsta060** [comment]
Bare in mind i have deleted and reinstalled ulx to fix the issue but that hasn't worked

**Comment by Nayruden** [comment]
Looks like you deleted your admin group. This is not a bug in ULX. If you want to reset ULX, you can run "ulx resettodefaults". FAdmin occasionally tries to send ULX broken configs as well, so you may need to reset that as well.
