### ISSUE TITLE
ulx menu dont show

### ISSUE THREAD

**Issue by FunnyCraft** [TeamUlysses/ulx#142]
### Steps to reproduce
1. Join to server

### Expected behavior
https://media.discordapp.net/attachments/531270135764221953/538461824497221632/unknown.png

### Actual behavior
https://media.discordapp.net/attachments/531270135764221953/538461824497221632/unknown.png

### Error(s) in server console, if any

Lickoy|2441|STEAM_0:1:233341602

[ERROR] Unauthed player
  1. query - [C]:-1
   2. refresh - addons/ulx/lua/ulx/xgui/commands.lua:302
    3. unknown - addons/ulx/lua/ulx/xgui/commands.lua:391
     4. include - [C]:-1
      5. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:137
       6. Call - addons/ulib/lua/ulib/shared/hook.lua:109
        7. fn - addons/ulib/lua/ulib/cl_init.lua:49
         8. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

Lickoy|2441|STEAM_0:1:233341602

[ERROR] Unauthed player
  1. query - [C]:-1
   2. processModules - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:221
    3. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:175
     4. Call - addons/ulib/lua/ulib/shared/hook.lua:109
      5. fn - addons/ulib/lua/ulib/cl_init.lua:49
       6. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

### Version

ULX version: v3.73d (03/21/17)

**Comment by JamminR** [comment]
Multiple posts of this on our forum.
Reference search results "unauthed" https://forums.ulyssesmod.net/index.php?action=search2;params=eJwtzcEKwjAMBuB38eIlh8W6gU9TuiRQR20la5VBH95Udgl_Pv6QwJ-QSbhf-9QvfdWRZkDAOzgEZ3MBtDAB3gBncA4MHtbdY_l6Kq93kip2Naitm1D1JafjlKLVkkqS_6OTPD_VmGWnIRKUou0th1aj8A9RDjSX
99% of the time, it's due to another addon breaking spawn hook, not ULib.
Look for further errors during server startup.

**Comment by FunnyCraft** [comment]
it does not immediately break, today only after 18 hours of operation the server broke

**Comment by JamminR** [comment]
Every time, or random, it is still believed to be other's code.
See answer to another random - https://forums.ulyssesmod.net/index.php/topic,6192.msg29344.html#msg29344
**Every time so far** someone has solved it for themselves in our forum, it's been another addon causing it, as you can find in the posts that found solutions from our previously posted search link.

**Comment by FunnyCraft** [comment]
I still have not solved the problem, it breaks down after 10-20 hours of server operation, idk.

**Comment by JamminR** [comment]
Did you follow the previously provided troubleshooting?
Run ONLY the game from a fresh install, subscribe to none/install no other addons but ULX/Ulib.
https://forums.ulyssesmod.net/index.php/topic,8922.msg45633.html#msg45633

**Comment by Nayruden** [comment]
Closing due to non-response
