### ISSUE TITLE
Nutscript 1.1 ULX Lagg

### ISSUE THREAD

**Issue by ThomasTwoFace** [TeamUlysses/ulx#143]
### Steps to reproduce
1.Run the server as normal
2.Wait for the serve to populate 
3. Extream lagg that affects everyone to the point that people cant move

### Expected behavior
Extreme lagg to the point that people cant move or drive

### Actual behavior
Please find the enclosed screenshot

### Version
Run "ulx version" in console and paste the result
![nutscript](https://user-images.githubusercontent.com/47926853/53290474-18ae1b00-379c-11e9-9073-98015dacd8f5.PNG)

**Comment by Nayruden** [comment]
Where are you pulling your version of Nutscript from? The main repository doesn't have anything like that -- https://github.com/rebel1324/NutScript

**Comment by ThomasTwoFace** [comment]
I'm using nutscript 1.1 beta

**Comment by Nayruden** [comment]
Still don't see anything like that inside the beta branch. Do you still have this issue using the release version?

**Comment by ThomasTwoFace** [comment]
This message comes up on my servers concole as a warning message to anyone using nutscript 1.1 or above.

**Comment by Nayruden** [comment]
Not sure why OP is getting this message, but Google pulls up nothing about any ULX/Nutscript conflicts and ULX is actually recommended by the developers -- https://nutscript.miraheze.org/wiki/Installing_Nutscript .
