### ISSUE TITLE
ulx gui issue

### ISSUE THREAD

**Issue by brandon123332** [TeamUlysses/ulx#144]
### Steps to reproduce
1.load in to the server
2. select character
3. press bind, or do !menu or xgui in console

### Expected behavior
i should be able to go into the ulx menu

### Actual behavior
gives me a box saying a gui error happened

### Error(s) in server console, if any
///////////////////////////////////////
//  ULX GUI -- Made by Stickly Man!  //
///////////////////////////////////////
// Loading GUI Modules...            //
//   bans.lua                        //

[ERROR] Unauthed player
  1. query - [C]:-1
   2. refresh - addons/ulx/lua/ulx/xgui/commands.lua:302
    3. unknown - addons/ulx/lua/ulx/xgui/commands.lua:391
     4. include - [C]:-1
      5. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:142
       6. Call - addons/ulib/lua/ulib/shared/hook.lua:110
        7. fn - addons/ulib/lua/ulib/cl_init.lua:49
         8. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

//   commands.lua                    //
//   groups.lua                      //

[ERROR] Unauthed player
  1. query - [C]:-1
   2. updateVoteMaps - addons/ulx/lua/ulx/xgui/maps.lua:88
    3. unknown - addons/ulx/lua/ulx/xgui/maps.lua:163
     4. include - [C]:-1
      5. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:142
       6. Call - addons/ulib/lua/ulib/shared/hook.lua:110
        7. fn - addons/ulib/lua/ulib/cl_init.lua:49
         8. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

//   maps.lua                        //
//   settings.lua                    //
// Loading Setting Modules...        //
//   client.lua                      //
//   server.lua                      //
// Loading Gamemode Module(s)...     //
//   No module found!                //
// Modules Loaded!                   //
///////////////////////////////////////

[ERROR] Unauthed player
  1. query - [C]:-1
   2. processModules - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:235
    3. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:189
     4. Call - addons/ulib/lua/ulib/shared/hook.lua:110
      5. fn - addons/ulib/lua/ulib/cl_init.lua:49
       6. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

### Error(s) in player's console, if any
///////////////////////////////////////
//  ULX GUI -- Made by Stickly Man!  //
///////////////////////////////////////
// Loading GUI Modules...            //
//   bans.lua                        //

[ERROR] Unauthed player
  1. query - [C]:-1
   2. refresh - addons/ulx/lua/ulx/xgui/commands.lua:302
    3. unknown - addons/ulx/lua/ulx/xgui/commands.lua:391
     4. include - [C]:-1
      5. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:142
       6. Call - addons/ulib/lua/ulib/shared/hook.lua:110
        7. fn - addons/ulib/lua/ulib/cl_init.lua:49
         8. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

//   commands.lua                    //
//   groups.lua                      //

[ERROR] Unauthed player
  1. query - [C]:-1
   2. updateVoteMaps - addons/ulx/lua/ulx/xgui/maps.lua:88
    3. unknown - addons/ulx/lua/ulx/xgui/maps.lua:163
     4. include - [C]:-1
      5. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:142
       6. Call - addons/ulib/lua/ulib/shared/hook.lua:110
        7. fn - addons/ulib/lua/ulib/cl_init.lua:49
         8. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

//   maps.lua                        //
//   settings.lua                    //
// Loading Setting Modules...        //
//   client.lua                      //
//   server.lua                      //
// Loading Gamemode Module(s)...     //
//   No module found!                //
// Modules Loaded!                   //
///////////////////////////////////////

[ERROR] Unauthed player
  1. query - [C]:-1
   2. processModules - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:235
    3. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:189
     4. Call - addons/ulib/lua/ulib/shared/hook.lua:110
      5. fn - addons/ulib/lua/ulib/cl_init.lua:49
       6. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

### Version
ULib v2.61
ULX v3.71
 
but it happens on every version i have tried

**Comment by Nayruden** [comment]
You may have another addon that's crushing all Lua hooks. Can you try running on a server with no other addons?

**Comment by joeyjumper94** [comment]
still no

**Comment by joeyjumper94** [comment]
look at garrysmod/data/ulib/groups.txt
is it bigger than say 50 KB?
if it is it may be trying to write 64KB onto a net message

**Comment by Nayruden** [comment]
No response in over two weeks, closing.
