### ISSUE TITLE
group assignment problem

### ISSUE THREAD

**Issue by Drfleam** [TeamUlysses/ulx#147]
### Steps to reproduce
1.
2.
3.

### Expected behavior
I should be able to give myself the super admin role and have a groups tab in the menu

### Actual behavior
I cannot add myself to any role or see a groups tab in the menu

### Error(s) in server console, if any
ulx adduser Ostrich superadmin
Unknown command "ulx_adduser"

### Error(s) in player's console, if any
N/A

### Version
Run "ulx version" in console and paste the result
ULib v2.63
ULX v3.73

**Comment by Nayruden** [comment]
You almost certainly have errors during the server startup/map change. Can you paste those here?

**Comment by joeyjumper94** [comment]
try replacing the underscore "_" with a space " "

**Comment by Nayruden** [comment]
No response is over two weeks, closing.
