### ISSUE TITLE
When i type in !menu for ULX it doesnt do anything

### ISSUE THREAD

**Issue by benthegamingguy09** [TeamUlysses/ulx#149]
### Steps to reproduce
1. I binded my key to do !menu but it saids this in console Unknown command: !menu
2. There are no lua errors giving off in console
3. 

### Expected behavior
Tell us what should happen
Well before i was typing !menu in chat on my server and it was working %100 so i dont know whats going on with it its updated and i just downloaded it. but now its not working I believe everytime i make new groups in ulx it always likes to not work anymore but i never touched the default ranks in ulx which it comes with. 

### Actual behavior
Tell us what happens instead

### Error(s) in server console, if any
No errors in console i checked over and over and over its giving off nothing

### Error(s) in player's console, if any
No errors in console i checked over and over and over its giving off nothing

### Version
Run "ulx version" in console and paste the result
This server is running ULX Admin Mod v3.73 by Team Ulysses from ulyssesmod.net

So if anyone could help me with this and explain every little thing in detail that would be amazing. 
    Thank you

**Comment by Nayruden** [comment]
Does `ulx menu` in console work? If so, you have a conflicting addon.

**Comment by benthegamingguy09** [comment]
Ok so ulx menu in console does work. So if it works in console does that mean i have to go there everytime to open it or what?

**Comment by Nayruden** [comment]
No, it means you have a conflicting addon. One of your addons is grabbing all "chat commands" and not passing them on to other addons that may need that information (such as ULX). You can remove all addons and add them back in one by one to figure out which one it is.

**Comment by benthegamingguy09** [comment]
Ok i will do that thank you so much for the info. I greatly appreciate your help. Thank you for taking the time to come and help
   have a great day
