### ISSUE TITLE
Conflicts with pac3

### ISSUE THREAD

**Issue by thegrb93** [TeamUlysses/ulx#152]
https://github.com/CapsAdmin/pac3/issues/767

Idk what the issue is, I don't use ULX, but there is apparently a conflict.

**Comment by Nayruden** [comment]
Hook order is not guaranteed in gmod; if a different order is causing the issue, the hook needs to be written to take that possibility into account. We followed the same ordering Garry did as of a few years ago, but I won't make a change for something that's not documented or guaranteed in the first place.

**Comment by thegrb93** [comment]
Nobody said it was hook order, that was only a guess since that's the only thing I know ulx fucks with, but it's probably something else.

**Comment by thegrb93** [comment]
Problem was traced to UTime
