### ISSUE TITLE
Invalid command entered

### ISSUE THREAD

**Issue by CLEVELANDMAN99** [TeamUlysses/ulx#153]
### Steps to reproduce
1.Start server
 Upon server start my console is being spammed with 
Invalid command entered. If you need help, please type "ulx help" in your console.
Invalid command entered. If you need help, please type "ulx help" in your console.
Invalid command entered. If you need help, please type "ulx help" in your console.
Invalid command entered. If you need help, please type "ulx help" in your console.
Even though no commands are being entered. How can I fix this issue?

**Comment by Nayruden** [comment]
We use GitHub issues for bug reports. For help and support, please visit our forums or Discord.
