### ISSUE TITLE
Doing !speed for everyone

### ISSUE THREAD

**Issue by ShadowzOfTheDark** [TeamUlysses/ulx#157]
Do "!speed * 0 0"

"You reset the walk and run speed for Everyone" message should be printed once

"You reset the walk and run speed for Everyone" message is printed for each player on the server.

No error in server console.

No error in client console.

ULib v2.63w
ULX v3.73w

**Comment by Nayruden** [comment]
This is not a command included in ULX, please send this information to the appropriate plugin author.
