### ISSUE TITLE
HTTPS-seeming sites show up as just grey as the MOTD?

### ISSUE THREAD

**Issue by Fires1** [TeamUlysses/ulx#158]
### Steps to reproduce
1. Use an HTTPS URL as an motd

### Expected behavior
On my side, I see the site (https://zzzzz.dev/ttt/tttmotd) 

### Actual behavior
For many of my players they see nothing but just a gray default background

### Version
ULib v2.63
ULX v3.73

**I am using the 64bit chromium version** which is what I likely conclude to be the issue

Would it be possible to detect what version of the game the player is on and default to the local file version? I encountered the same issue with the local files until I removed all CSS content which I believe had a weird mix of HTTP and HTTPS content.

I imagine this is HEAVILY outside the control of ULX but if there was a possible way to fall back that'd be nice

**Comment by Nayruden** [comment]
You're using Let's Encrypt for your CA, which is not incredibly widely supported. I'd recommend going with a different CA or falling back on http. You are right that Chromium is outside our control.
