### ISSUE TITLE
Getting Ban Data: Error

### ISSUE THREAD

**Issue by Zulbem** [TeamUlysses/ulx#159]
### Steps to reproduce
1. This started happening since I updated to the latest version of ULX, then I tried to revert but the error still occurred.

### Expected behaviour
The data should go through to the client and the bans should appear.

### Actual behaviour
Once you load into the server and then ulx tries to obtain ban data, it fails at around 90-99% and replies back with an error in both server and client console.

### Error(s) in server console, if any
[Player|713|STEAM_0:1:7817445] Lua Error:
[ERROR] lua/includes/extensions/table.lua:50: bad argument #1 to 'pairs' (table expected, got nil)
1. pairs - [C]:-1
2. Empty - lua/includes/extensions/table.lua:50
3. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:464
4. func - addons/ulib/lua/ulib/client/cl_util.lua:22
5. unknown - lua/includes/extensions/net.lua:32

### Error(s) in player's console, if any
[ERROR] lua/includes/extensions/table.lua:50: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. Empty - lua/includes/extensions/table.lua:50
    3. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:464
     4. func - addons/ulib/lua/ulib/client/cl_util.lua:22
      5. unknown - lua/includes/extensions/net.lua:32

**Comment by Nayruden** [comment]
What version are you using that you got this error on? If you went to the
development version (on Git) and then to a release version, we don't offer
a downgrade path -- you'll need to clear out your data or go back to the
development version.

**Comment by Zulbem** [comment]
ULib v2.63d (05/12/18)
ULX v3.73d (02/11/18)

**Comment by Zulbem** [comment]
This was caused by uTime for anyone wondering.
