### ISSUE TITLE
Ulx Menu isn't working

### ISSUE THREAD

**Issue by GlopTheGlasp** [TeamUlysses/ulx#161]
### Steps to reproduce
1.Any of the ways to open the ulx menu
2.
3.

### Expected behavior
The menu should open

### Actual behavior
The menu doesn't open

###

### Version
`The "ulx version" command registers as an unknown command.

**Comment by GlopTheGlasp** [comment]
Yes I have the addon enabled, but I think it's acting like it's not.

**Comment by AlternativeGM** [comment]
Ulib enable? (libraly for ULX)

**Comment by Nayruden** [comment]
This area is for bug reports, sounds like you need help setting up ULX. Please use our forums or Discord for help and support.
