### ISSUE TITLE
Panel error occurs sometimes

### ISSUE THREAD

**Issue by ceifa** [TeamUlysses/ulx#166]
### Steps to reproduce
1. Install ULX in a server with high userbase.
2. Check the clientside_errors.txt after some hours

### Expected behavior
No errors.

### Actual behavior
Errors when opening the xgui.

### Error(s) in player's console, if any
> DPropertySheet:AddSheet tried to add invalid panel!

### Version
ULib v2.63
ULX v3.73

**Comment by iViscosity** [comment]
Is this the same issue as #167 ?

**Comment by ceifa** [comment]
I really don't know. I couldn't reproduce and I just saw it polluting a lot the `clientside_errors` file.
Sorry for the lack of informations. Feel free to close the PR too :/
