### ISSUE TITLE
ULX Menu Panel Broke :(

### ISSUE THREAD

**Issue by SlyGuy7** [TeamUlysses/ulx#167]
### Steps to reproduce
1. I have a bind to pull up the ulx menu
2. If the bind doesn't work I just type !menu

### Expected behavior
Tell us what should happen
When I press my bind, the standard ULX menu should pop up with 3 tabs: Commands, Settings, Maps

### Actual behavior 
Tell us what happens instead
**It's completely blank (Screenshot included)**
![ULX Menu Issue 1](https://user-images.githubusercontent.com/67987469/86863663-a771be00-c099-11ea-8cac-e44105c2ad49.PNG)

### Error(s) in server console, if any
**N/A**

### Error(s) in player's console, if any
![ULX Menu Issue 3](https://user-images.githubusercontent.com/67987469/86863916-2b2baa80-c09a-11ea-9293-bcdcd5345516.PNG)

### Version
Run "ulx version" in console and paste the result
**ULib v2.63d (05/12/18)
ULX v3.73d (05/20/18)**

**Comment by iViscosity** [comment]
It's likely this error occurs because you have installed a custom skin for XGUI (which isn't well implemented or supported). If you go to `garrysmod/data/ulx` and delete `xgui_settings.txt`, it will reset and regenerate XGUI settings. 

If you did NOT install a custom skin, there may be a problem in your ULX installation. Have you tried reinstalling?

**Comment by SlyGuy7** [comment]
That fixed it, thank you so much. <3

**Comment by NoxTGA** [comment]
Hello, I have the same issue, I installed a custom skin but I can't find the file `xgui_settings.txt` in the data `garrysmod/data/ulx`. I don't know what to do and it's very annoying not being able to use the ulx menu.

**Comment by iViscosity** [comment]
Make sure you're looking at your client files, not the server files. It should be `garrysmod/data/ulx/xgui_settings.txt`

**Comment by NoxTGA** [comment]
@iViscosity you're the best thank you
