### ISSUE TITLE
ULIB + ULX are running ISteamHTTP too early in latest version of gmod

### ISSUE THREAD

**Issue by lolteam4u** [TeamUlysses/ulx#174]
### Steps to reproduce
1.Update server with darkrp
2.place ulx on there
3 start server

### Expected behavior
Tell us what should happen
Not to spit our a lua error on start up

### Actual behavior
Gices a lua error

### Error(s) in server console, if any
[ulib] HTTP failed - ISteamHTTP isn't available!
   2. fn - addons/ulib/lua/ulib/shared/plugin.lua:186
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:109
  1. Fetch - lua/includes/modules/http.lua:42
### Error(s) in player's console, if any
None
### Version
Run "ulx version" in console and paste the result
ULib v2.63
ULX v3.73

**Comment by Nayruden** [comment]
ULX and ULib don’t call that library—ask for help from the author of the add on you’re using.

**Comment by Timmy** [comment]
ULib makes a HTTP request when checking for updates. The first call happens in the Initialize hook. Apparently that's too early, and it triggers the "HTTP failed" error...

The error disappears when commenting https://github.com/TeamUlysses/ulib/blob/c44d23fd82e394982eb361516140757f2fabcc54/lua/ulib/shared/plugin.lua#L190.

**Comment by lolteam4u** [comment]
@Nayruden this fix worked above this is defo an issue with the updater

**Comment by Nayruden** [comment]
@Timmy you are right, my bad for speed reading the issue. I had thought ISteamHTTP only applied to calling the Steam APIs, which we don't do. Re-opening issue.

**Comment by iViscosity** [comment]
I believe MrP just [pushed a fix to this](https://github.com/TeamUlysses/ulib/commit/e08eec2cbcfc5906e6548bede1b4c465659dd35f) a few days ago. Update your ULib and check if it is still erroring on you 👍

**Comment by SpiffyJUNIOR** [comment]
Still getting the exact same error on latest workshop ulib and ulx versions.

**Comment by FlorianLeChat** [comment]
The fixes made on the GitHub repository were never applied to the Workshop version. The last update of ULX/ULIB is from 2017 so there is already more than 5 years behind. Server owners should use the GitHub version instead of the Workshop version if they want to get the latest bug and security fixes.

**Comment by SpiffyJUNIOR** [comment]
> The fixes made on the GitHub repository were never applied to the Workshop version. The last update of ULX/ULIB is from 2017 so there is already more than 5 years behind. Server owners should use the GitHub version instead of the Workshop version if they want to get the latest bug and security fixes.
Had no idea that was the situation with the workshop versions, sorry for the confusion

**Comment by zpetty33** [comment]
Issue was resolved with https://github.com/TeamUlysses/ulib/commit/e08eec2cbcfc5906e6548bede1b4c465659dd35f
