### ISSUE TITLE
Attempt to index local 'arg' (a number value)

### ISSUE THREAD

**Issue by tavaius** [TeamUlysses/ulx#176]
### Steps to reproduce
1. Open the XGUI menu.
2. Edit permissions for a ulx role
4. Select "ulx votegag" under "voting"
3. Error will occur, freezing your xgui.

### Expected behavior
I should be able to select, untick/tick "ulx votegag".

### Actual behavior
An "attempt to index local 'arg' (a number value)" error occurs, freezing my menu.

### Error(s) in server console, if any

N/A

### Error(s) in player's console, if any

[ulx-master] addons/ulx-master/lua/ulx/modules/cl/xgui_helpers.lua:338: attempt to index local 'arg' (a number value)
  1. getTime - addons/ulx-master/lua/ulx/modules/cl/xgui_helpers.lua:338
   2. obj - addons/ulx-master/lua/ulx/xgui/groups.lua:674
    3. func - addons/ulx-master/lua/ulx/modules/cl/xlib.lua:1151
     4. animQueue_call - addons/ulx-master/lua/ulx/modules/cl/xlib.lua:1132
      5. func - addons/ulx-master/lua/ulx/modules/cl/xlib.lua:1151
       6. animQueue_call - addons/ulx-master/lua/ulx/modules/cl/xlib.lua:1132
        7. Stop - addons/ulx-master/lua/ulx/modules/cl/xlib.lua:1079
         8. Run - addons/ulx-master/lua/ulx/modules/cl/xlib.lua:1086
          9. fn - addons/ulx-master/lua/ulx/modules/cl/xlib.lua:1096
           10. Call - addons/ulib-master/lua/ulib/shared/hook.lua:109
            11. unknown - addons/ulx-master/lua/ulx/modules/cl/xgui_helpers.lua:31

### Version
Run "ulx version" in console and paste the result

ULib v2.63d (05/12/18)
ULX v3.73d (05/21/18)

**Comment by zpetty33** [comment]
Hi there! votegag is not a command in ULX. It's possible that you have a 3rd party votegag command plugin that wasn't configured correctly. I am not able to reproduce this issue with any of the other vote commands.
