### ISSUE TITLE
I use ulx restrictions, and it doesnt like to work sometimes, there are certain restrictions for certain items that dont work, like you can restrict it, but it wont actually restrict it, for example the sgm boats, and the flammpanzer for gredwitch, those are just some examples

### ISSUE THREAD

**Issue by datboi47** [TeamUlysses/ulx#177]
### Steps to reproduce
1. use ulx restrictions and try restricting sgm boats
2. use ulx restrictions and try restricting gredwitch flammpanzer
3.

### Expected behavior
Tell us what should happen
It should restrict properly
### Actual behavior
Tell us what happens instead
Anyone can spawn them even if restricted
### Version
Run "ulx version" in console and paste the result
 ULib v2.63w
ULX v3.73w

**Comment by Nayruden** [comment]
Restrictions are not part of ULX by default. Are you using a third-party addon for restrictions?
