### ISSUE TITLE
super admin and admin not able to us commands in the tab menu

### ISSUE THREAD

**Issue by blarg2-5** [TeamUlysses/ulx#181]
### Steps to reproduce
unsure as of now

### Expected behavior
Tell us what should happen
N/A
### Actual behavior
Tell us what happens instead
so I'm able to use commands in the !menu menu but not in the tab menu and I have tried to restart and redownload ulx 2 now not fixing it
### Error(s) in server console, if any
1. error - [C]:-1
   2. doInclude - gamemodes/darkrp/gamemode/libraries/simplerr.lua:530
    3. loadCustomDarkRPItems - gamemodesCouldn't Load Init Script: 'darkrp/gamemode/init.lua'
### Error(s) in player's console, if any
N/A
### Version
Run "ulx version" in console and paste the result
not able to when put in just gos to the next line

**Comment by zpetty33** [comment]
This is an error in some custom DarkRP content you have installed.
