### ISSUE TITLE
No automatic unban

### ISSUE THREAD

**Issue by Serpensin** [TeamUlysses/ulx#186]
### Steps to reproduce
1. Ban via XGUI (Via Name, not ID)--> Length 1 Minute
2. Wait 1 Minute (or more - doesn't matter)

### Expected behavior
There should be an automated unban at the end of the duration.

### Actual behavior
Doesn't unban automaticly.

### Error(s) in server console, if any
`Serpensin (STEAM_0:1:464587047)<IP:PORT> was kicked by ULib because they are on the ban list
IP:PORT:  password failed.
`

### Error(s) in player's console, if any
Just the BANNED MEssage with no time left

### Version
ULib v2.63w
ULX v3.73w

The Server is running on Ubuntu Server 20.04.2 LTS

**Comment by sunset-developer** [comment]
An unban happens on server restart or map change I'm pretty sure.

**Comment by Serpensin** [comment]
Thx, it's working that way. Didn't know that. 😊
