### ISSUE TITLE
Does ULX leak location data?

### ISSUE THREAD

**Issue by Cats869** [TeamUlysses/ulx#187]
More of a question since I keep hearing these rumors spread that ULX leaks location data (whatever that exactly means). I want to hear from the devs of this addon if this is true or false. If this is true, I wonder how significant this kind of issue would be. Thanks.

**Comment by garryspins** [comment]
like... gps coordinates? absolutely not
even IPs arent stored by my knowledge 

so no

**Comment by FarukGamer** [comment]
See here https://github.com/CapsAdmin/pac3/pull/69

**Comment by Cats869** [comment]
> See here [CapsAdmin/pac3#69](https://github.com/CapsAdmin/pac3/pull/69)

If Steam IDs the only way that ULX could leak location data, then I think that would be pretty minor since you could get anyone's Steam ID in a server just by typing status in console on the client side.

**Comment by garryspins** [comment]
I dont think you understand steamids, steamids in NO way correlate to locations

**Comment by Cats869** [comment]
> I dont think you understand steamids, steamids in NO way correlate to locations

Exactly. I'm not sure why the guy who posted here after you posted that. Apparently the person just deleted their post.

**Comment by storm37000** [comment]
I would be more concerned with sourcebans distributing peoples IPs.  Most really bad banned people will be using VPNs.  Banning by IP is next to useless and has more collateral damage when ISPs rotate IPs around and you end up banning a random innocent person in the end.

**Comment by zpetty33** [comment]
ULX doesn't collect or log IP address. We give server's the OPTION to authenticate a user by IP address, but that would need to be input by the server admin. ULX doesn't store or collect IP addresses at all.
