### ISSUE TITLE
ULX resettodefaults does not clear ban database after SQL migration.

### ISSUE THREAD

**Issue by Codingale** [TeamUlysses/ulx#192]
### Description
Since https://github.com/TeamUlysses/ulib/commit/0b4cdd0acbf86597446dee4576e7ece9aea15999 the database has been SQL based however the resettodefaults command was not also updated. https://github.com/TeamUlysses/ulx/blob/afca346273a12c8267227b843bee646e5ec947ed/lua/ulx/modules/sh/util.lua#L396
### Expected behavior
resettodefaults should reset the ban database, but since it was migrated to SQL it was not updated to clear the table.

### Actual behavior
It just deletes the `bans.txt` file, and does not clear SQL.

Writing this really late after a long day, so pardon me if I'm mistaken, I haven't actually tried it but I think I understand this correctly.

**Comment by zpetty33** [comment]
Fixed in v3.81
