### ISSUE TITLE
Ulx broken due to ULib net-message rework

### ISSUE THREAD

**Issue by ZenBre4ker** [TeamUlysses/ulx#195]
### Steps to reproduce
1. Use Github ULib with Ulx

### Expected behavior
Ulx should work

### Actual behavior
Ulx crashes the server

Ulx uses a number instead of a string for the default_value.
https://github.com/TeamUlysses/ulx/blob/master/lua/ulx/xgui/server/sv_settings.lua#L16-L22

Also please do a fail-safe inside ULib as many older addons just like Ulx itself proves here, are using actual values instead of strings for this function. Since the rework with the net-library the error occurs:
https://github.com/TeamUlysses/ulib/commit/09c4e751a1deaec6202c7c5c23a8b11205720956#diff-dbb40aa172e92e98991fa2750b461bafed33dcc0bbe765cc2b40b32f159daa5cL196-R133

You could use this simple PR and just safely convert it to strings:
https://github.com/TeamUlysses/ulib/pull/82

Also tried to argue it here, with an error of an addon causing the whole gamemode to fail:
https://github.com/TeamUlysses/ulib/issues/81

### Version
ULib v2.70w
ULX v3.73w

**Comment by ZenBre4ker** [comment]
Is Fixable via https://github.com/TeamUlysses/ulib/pull/82

**Comment by zpetty33** [comment]
Fixed in ULib.
[TeamUl](https://github.com/TeamUlysses/ulib/pull/82)
