### ISSUE TITLE
The text labels in the voting window look compressed in zombiesurvival gamemode

### ISSUE THREAD

**Issue by comminux** [TeamUlysses/ulx#197]
### Steps to reproduce
1. Download last git version of https://github.com/JetBoom/zombiesurvival
2. Open vote menu settings
3. Increase the number of voting options
4. Press "ulx vote" button

### Expected behavior
The voting parameters must have a non-zero vertical margin, similar to how it works in other gamemodes.

### Actual behavior
The voting parameters are compressed as if there are no margins

### Error(s) in server console, if any
None

### Error(s) in player's console, if any
None

### Version
ULib v2.70d (05/12/2018)
ULX v3.73d (05/21/2018)
https://github.com/TeamUlysses/ulx/commit/371a4fba6248e4f06df4cd30f96c59622752eaed

Attached images:
![Sandbox Vote Menu](https://user-images.githubusercontent.com/14937307/148612224-44d47fa9-f2e0-49b1-bf43-9a8cfcfb53f4.png)
![Sandbox Vote Result](https://user-images.githubusercontent.com/14937307/148612229-3d3fb875-8e21-4846-8c19-7b1d41ad803f.png)
![ZS Vote Menu](https://user-images.githubusercontent.com/14937307/148612234-098ece45-e382-4efe-845f-95202ca41551.png)
![ZS Vote Result](https://user-images.githubusercontent.com/14937307/148612239-d16d7726-e993-4a99-9b77-237033ce91a4.png)

**Comment by zpetty33** [comment]
ZombieSurvival gamemode overrides some gmod global variables related to VGUI text placement (super hacky and will break a lot of non ZS stuff).
When ULX calls this variable to use it in the voting menu, it displays wrong because ZS had overwritten it, it seems. This is a ZS issue and can't be fixed in ULX.
