### ISSUE TITLE
need help for some reason I can't set up the rights

### ISSUE THREAD

**Issue by 2006lev-Web** [TeamUlysses/ulx#198]
I have a problem , for some reason my rights are not shown and I can 't add rights, I have a superadmin user, please tell me what to do
![Screenshot_9](https://user-images.githubusercontent.com/64630503/149615497-51ce0a20-862f-4dd9-bdc9-9f30d50222a9.png)

### Version
ulx version
ULib v2.70d (05/12/18)
ULX v3.73
Русифицировал Aleksandr Confidential в 2019 году

**Comment by iViscosity** [comment]
Do you have any errors in your server's console either during boot or when you open the menu? Have you installed both addons properly?

Also, make sure you're using the latest versions of ULX and ULib from the GitHub repositories ([ULib](https://github.com/TeamUlysses/ulib/archive/refs/heads/master.zip) [ULX](https://github.com/TeamUlysses/ulx/archive/refs/heads/master.zip)).
