### ISSUE TITLE
Inconsistent player identification across your hook

### ISSUE THREAD

**Issue by Zulbem** [TeamUlysses/ulx#201]
https://github.com/TeamUlysses/ulx/blob/fc12a010e4bf93975a5547203c7d97751500fcdc/lua/ulx/modules/sh/user.lua#L90

As seen by the line above, it uses the players' unique ID to remove the user from their group, however, the wiki for ulib says for hook "ULibUserRemoved", 1st argument is steamid which is indeed correct when ulx removeruserid is called. As seen, this causes conflict with the informaton given

**Comment by Nayruden** [comment]
https://github.com/TeamUlysses/ulib/blob/e08eec2cbcfc5906e6548bede1b4c465659dd35f/lua/ulib/server/ucl.lua#L923 is where the hook is generated. I think you may be confusing the functions with the hooks.

**Comment by Zulbem** [comment]
I tested it the hook receives unique I'd when ulx remove user is called
