### ISSUE TITLE
Server freeze for 1minute when loading ULX

### ISSUE THREAD

**Issue by modcrafts** [TeamUlysses/ulx#208]
After it loads the ULX modules, it's as if the server freezes for a few minutes. This happens on Server Start, Map Change and anything involving having to reload modules. 
And during this time, the CPU load reached 100%

### Steps to reproduce
1. install ulx and ulib
2. start the server

### Expected behavior
no any startup lag

### Actual behavior
frozen for at least 1 minute
### Version
Ulib v2.70w
ULX v3.80w

**Comment by zpetty33** [comment]
Can you download and try the Experimental branch of ULib.
https://github.com/TeamUlysses/ulib/tree/Experimental

I am interested in if you have this issue with the changes we've made to user loading.

**Comment by modcrafts** [comment]
Sorry, the problem still exists

**Comment by zpetty33** [comment]
you likely have something conflicting then. Can you try removing ALL addons except ULX and ULib and see if the problem persists?

**Comment by modcrafts** [comment]
Yes, only ULX and ULib

**Comment by ApertureDevelopment** [comment]
Could you tell us a bit more about the environment you are in? 

What OS is the server on?
How exactly does this lag occur? / What do you see? ( a video of it happening would be really helpful )
How big is your ulx and ulib data folder?

( and propably more questions I forgot )

**Comment by modcrafts** [comment]
Oh, well
I'm so sorry, it's my map's problem 😂
