### ISSUE TITLE
When I Use "!menu" The Menu Automatically Closes As Soon As It Opens and Moves My Player Curser

### ISSUE THREAD

**Issue by Mayonetic** [TeamUlysses/ulx#210]
### Steps to reproduce
1. type !menu
2. thats it

### Expected behavior
Tell us what should happen
a. The menu should open as normal

### Actual behavior
Tell us what happens instead
a. The menu opens and then immediately closes and my player looks to the left

### Error(s) in server console, if any
a. no errors in console

### Error(s) in player's console, if any
a. no errors in console

### Version
Run "ulx version" in console and paste the result
ULib v2.63
ULX v3.73

Please Help

**Comment by SticklyMan** [comment]
I did a quick test and this is working just fine for me. If this is still an issue, can you report back with your graphics settings (resolution, fullscreen mode) and your operating system? This likely is just a bug in Garry's Mod that may be outside of our control.

**Comment by SticklyMan** [comment]
Closed as no response, please reach out again if you are continuing to experience issues. Or reach out on [our discord](https://discord.com/invite/gR4Uye6) for a higher chance for a faster response.
