### ISSUE TITLE
ulib fonctionne pas

### ISSUE THREAD

**Issue by LeoDupont1** [TeamUlysses/ulx#212]
sa me mais ça
 [ulib-v2_63] HTTP failed - ISteamHTTP isn't available!
  1. Fetch - lua/includes/modules/http.lua:42
   2. fn - addons/ulib-v2_63/lua/ulib/shared/plugin.lua:186
    3. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
qui pourrais m'aide

**Comment by FlorianLeChat** [comment]
Duplicated of #174. Update your ULX/ULiB version, because this issue has already been fixed. Next time, speak a minimal amount in english so other contributors can answer you 👍
