### ISSUE TITLE
Gwater Interference

### ISSUE THREAD

**Issue by luca1808** [TeamUlysses/ulx#214]
### Steps to reproduce
1. Load ANY map in multiplayer
2. Open the spawn menu
3. Open the Gwater tab

### Expected behavior
Custom tab should have something inside

### Actual behavior
Custom tab is COMPLETELY empty
![imageswe](https://github.com/TeamUlysses/ulx/assets/133994044/e4bee124-0e7b-4bc6-8574-537c8d354dc0)

### Error(s) in server console, if any

from problems menu. will not always show up.

 [GWater - Dynamic Water [v1.4]] lua/includes/extensions/table.lua:523: bad argument #1 to 'pairs' (table expected, got nil)
    1. pairs - [C]:-1
        2. toKeyValues - lua/includes/extensions/table.lua:523
            3. SortedPairsByMemberValue - lua/includes/extensions/table.lua:573
                4. DoPopulate - lua/autorun/client/cl_gwater_spawnmenu.lua:39
                    5. DoClick - lua/autorun/client/cl_gwater_spawnmenu.lua:51
                        6. InternalDoClick - lua/vgui/dtree_node.lua:63
                            7. fn - lua/autorun/client/cl_gwater_spawnmenu.lua:58
                                8. Call - lua/ulib/shared/hook.lua:109
                                    9. CallPopulateHook - gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/content.lua:54
                                        10. Function - lua/autorun/client/cl_gwater_spawnmenu.lua:81
                                            11. unknown - gamemodes/sandbox/gamemode/spawnmenu/creationmenu.lua:47
                                            
### Version
ULib v2.70w
ULX v3.80w

**Comment by ApertureDevelopment** [comment]
Like in my comment on #215 this issue is also not related or caused by ULib or ULX. You should contact the maintainers of gwater

**Comment by SticklyMan** [comment]
Closing due to lack of response. If our hook library is causing conflicts (and not just a bug in the addon itself), please have the author of gwater reach out to us so we can start a discussion about it.
