### ISSUE TITLE
Seamless portals errors

### ISSUE THREAD

**Issue by luca1808** [TeamUlysses/ulx#215]
### Steps to reproduce
1. Load ANY map in Multiplayer
2. Have Seamless portals installed

### Expected behavior
No errors

### Actual behavior
Errors get spammed into the console

### Error(s) in console, if any
[Seamless Portals] lua/autorun/client/cl_render_core.lua:62: attempt to compare nil with number
  1. fn - lua/autorun/client/cl_render_core.lua:62
   2. unknown - lua/ulib/shared/hook.lua:109

[Seamless Portals] lua/autorun/sh_portal_movement.lua:152: attempt to compare nil with number
  1. fn - lua/autorun/sh_portal_movement.lua:152
   2. unknown - lua/ulib/shared/hook.lua:109

### Version
ULib v2.70w
ULX v3.80w

**Comment by ApertureDevelopment** [comment]
This issue is unrelated to ULX and ULib. The reason it says ULib there is because ULib replaces the hook function with it's own logic.

**Comment by SticklyMan** [comment]
Closing due to lack of response. If our hook library is causing conflicts, please have the author of gwater reach out to us so we can start a discussion about it.
