### ISSUE TITLE
Gags can be bypassed by leaving and rejoining

### ISSUE THREAD

**Issue by obfuscatedgenerated** [TeamUlysses/ulx#216]
### Steps to reproduce
1. Gag a player
2. The player leaves and rejoins
3. They are no longer gagged

### Expected behavior
The gag is stored in memory on the server (with a longer lifetime than SetNWBool, at least until the server is stopped) and is immediately reapplied when they join back, unless ungagged.

### Actual behavior
Players can bypass gags by simply rejoining, which is frustrating when the only moderators online don't have ban permissions.

### Version
Run "ulx version" in console and paste the result

ULib v2.63d (02/16/18)
ULX v3.73d (03/21/17)

(I'm aware these are outdated but I don't see any changes made to the ulx.gag function since)

**Comment by zpetty33** [comment]
This is the expected behavior. There are some 3rd party pgag (persistent gag) modules out there to address this concern, but not really something that we would like to address officially.
