### ISSUE TITLE
Bans.txt does not generate (NOT BUG)

### ISSUE THREAD

**Issue by Gamersxp6248** [TeamUlysses/ulx#223]
### Steps to reproduce
1. Ban a user
2. Check bans.txt location
3. Nothing

### Expected behavior
I'm aware that the bans.txt file was removed... BUT WHY?! It was so easy to copy and paste series of steamid's into, I can no longer locate the location of the new bans file. Where is this file? Why was it moved?

I have a very very long list of steamid64's I need to paste into my bans, but I cannot as the file doesn't exist.

If there is no reliable method to view and write this information... can we please have an option to enable a legacy mode or something similar that doesn't suck?

### Version
Run "ulx version" in console and paste the result
ULib v2.71w
ULX v3.81w

**Comment by zpetty33** [comment]
Bans are stored in the sv.db file. SQLite is much more stable than flat text files. They're located in the ulib_bans table inside the database.

**Comment by Gamersxp6248** [comment]
> Bans are stored in the sv.db file. SQLite is much more stable than flat text files. They're located in the ulib_bans table inside the database.

So there is no easy way to open this file and edit it?

**Comment by sbzlzh** [comment]
> > Bans are stored in the sv.db file. SQLite is much more stable than flat text files. They're located in the ulib_bans table inside the database.
> 
> So there is no easy way to open this file and edit it?

I find it easy to use Navicat.
