### ISSUE TITLE
ulx is breaking my server bug

### ISSUE THREAD

**Issue by Jenssons** [TeamUlysses/ulx#23]
[Error] Lua Error: [ERROR] addons/ulx/lua/ulx/modules/xgui_server.lua:17: attempt to call local 'postinitFunc' (a nil value) 1. addSVModule - addons/ulx/lua/ulx/modules/xgui_server.lua:17 2. unknown - addons/ulx/lua/ulx/xgui/server/sv_sandbox.lua:45

is it my server or should i just wait for a update

**Comment by yupi2** [comment]
Have you tried restarting your server?

**Comment by Jenssons** [comment]
yes and reinstalling it

**Comment by yupi2** [comment]
@Jenssons #24 should fix this. If you were upgrading ULX you should turn your server off so Lua autorefresh errors don't happen.

**Comment by Jenssons** [comment]
the server was off and i wasnt updating it i was adding it to the server for the first time and again the server was off at the time

**Comment by yupi2** [comment]
@Jenssons I'm sorry for assuming things in that case then. Something is probably modifying the file, reloading the file, or is attempting to replace the Sandbox XGUI menu server code (which isn't a problem).

**Comment by SticklyMan** [comment]
Fixed with yupi2's PR. 8cc8684ace8c3c9e85e8b583e9bae6ee9099897d
