### ISSUE TITLE
ulx/ulib issue with darkrp mysql

### ISSUE THREAD

**Issue by alotlikebirds** [TeamUlysses/ulx#25]
When you have darkrp set up to mysql ulx resets fadmins ranks back to user after a server restart. After 4 days of debugging my server, I've narrowed it down to ulx/ulib. Having darkrp set up to SQLite while using ulx/ulib works flawlessly, but when darkrp is set to mySQL this bug occurs. Darkrp is not the issue since removing ulx/ulib fixes the problem. There are no error on the server nor the database, so it took me a long time to find out the cause, but if you can have ulx/ulib working with darkrp using SQLite why wouldn't it work when its set to mySQL? Any chance we can get a fix for this? ulx/ulib is very important on my server.  I am running the latest github for both ulx/ulib.

**Comment by Nayruden** [comment]
You will need to talk to FPtje about this, or the author of your SQL-DarkRP
module. There's nothing more we can do from our side.
