### ISSUE TITLE
Crashing with custom groups.

### ISSUE THREAD

**Issue by max8989** [TeamUlysses/ulx#26]
Hi guys.
When i giving any custom group to my friend (helper,vip, etc.) and his leaving from the server - server crashing, just shutting off
Last logs:
[15:44:25] Client "Nick" spawned in server <STEAM_0:0> (took 12 seconds).
[15:45:06] Brian Bridges added Nick to group helper
[15:45:12] Nick: !jail 
[15:45:15] Nick: !jai;
[15:45:17] Dropped "Nick" from server<STEAM_0:0>
*CRASH*

I tried to reinstall many times.
Thank you in andvance.
ulx-v3_62 and 2.52 ulib

**Comment by Nayruden** [comment]
What gamemode? Are there any errors in the server console while it's
crashing? Does it fully crash or does it simply hang?

**Comment by max8989** [comment]
Darkrp, there's no errors. Its just shutting off.

**Comment by Nayruden** [comment]
I'm sorry, but there's nothing we can do to help you with such limited
information. It works fine for most people.

A long time ago, I remember there being a cvar to enable lua error logging.
If that's still around, you could try enabling it (I can't find the cvar at
the moment, but I'll try looking around more in a few days, or you can try
to find it).

**Comment by max8989** [comment]
lua_log_sv maybe this?

**Comment by Nayruden** [comment]
That sounds right

**Comment by max8989** [comment]
Its fixed my itsfelf. I really dont know how, but this bug was about 2 weeks on my pc hosting and now 3-4 days on hosting. Ty so much for trying help. There's one intresting thing, 
before there's no group "no acess" now its add by itsself, and all works and now add "CAMI" cvars from darkrp.

**Comment by Nayruden** [comment]
Yes, the "no access" comes from DarkRP. Not sure what it's used for, but
DarkRP registers it with CAMI, so ULX picks it up.
