### ISSUE TITLE
ulx and ulib error with another server management

### ISSUE THREAD

**Issue by Frogurt** [TeamUlysses/ulx#27]
so i have ulx and ulib and they are working normally but when i downloaded another server management its giving me error so i removed that another server management but the ulx and ulib keep giving me the error with the darkrp jobs.Does anyone know how to fix this? please

**Comment by Nayruden** [comment]
We implement CAMI, which allows admin mods to talk to each other. If the other one is not implementing that, there is nothing we can do.
