### ISSUE TITLE
Inherit Problems

### ISSUE THREAD

**Issue by SeaLife** [TeamUlysses/ulx#30]
Hey guys,

here my Problem as short as possible:

I got these Groups on the Server:

| Group | Inherit |
| ----- | ---- |
| superadmin | admin |
| admin | operator/donator+ |
| operator/donator+ | operator/donator |
| operator/donator | operator |
| operator | member/donator+ |
| member/donator+ | user |
| member/donator | user |
| member | user |
| donator+ | user |
| donator | user |
| noaccess | user |

but i want to set them up like:

| Group | Inherit |
| ----- | ---- |
| superadmin | admin |
| admin | operator/donator+ |
| operator/donator+ | operator/donator |
| operator | member/donator+ |
| member/donator+ | member/donator |
| member/donator | member |
| member | donator+ |
| donator+ | donator |
| donator | user |
| noaccess | user |

If i set them up like this, everything higher then donator+ gains ACCESS_ADMIN flag...

(ply:IsAdmin() will be true on member)

i do not know why

**Comment by Nayruden** [comment]
Is this DarkRP?

**Comment by SeaLife** [comment]
Yes. Its DarkRP :)

**Comment by Nayruden** [comment]
ULib flags IsAdmin() for users who inherit from admin -- we unfortunately can't control how DarkRP overrides that function though.
