### ISSUE TITLE
ULX and FAdmin conflict ?

### ISSUE THREAD

**Issue by TontonBa** [TeamUlysses/ulx#33]
So, i created Darkrp server, installed the lastest updates and when i join and set me as superadmin via console "rcon ulx adduserid..." i get in the superadmin group and can use the menu and execute commands but when i'm on the tab menu have none of the commands (ban, kick, freeze...) and when i try to go on server settings it says "no access!".

[Screenshots]
http://www.noelshack.com/2016-08-1456348942-tabmenu.png
http://www.noelshack.com/2016-08-1456348941-tabmenu.png
http://www.noelshack.com/2016-08-1456348941-ulxmenu.png

Version
ulx v3.70
ulib v2.60

FPtje said:

"_it's ULX':

] lua_run_cl print(Player(3):GetNWString("usergroup"))
user
] lua_run_cl print(Player(3):GetUserGroup())
superadmin
] lua_run_cl show(FindMetaTable("Player").GetUserGroup)
function: 0x2b9d5b10    -- [addons/ulib/lua/ulib/shared/sh_ucl.lua]: 263-272
] lua_run print(Player(3):GetUserGroup())
> print(Player(3):GetUserGroup())...
user

ULib has overridden GetUserGroup and decided that clientside it should say "superadmin" while serverside it says "user". FAdmin uses GetUserGroup, so clientside, the player thinks they're superadmin."

**Comment by Nayruden** [comment]
You definitely have some issues there. Add me on Steam and we will try to
debug -- MegTech is my username. I will be on in about two hours from now.

**Comment by TontonBa** [comment]
I'm from Belgium and it's 00:03 am here ^^ aha let's try another day aha

**Comment by halfwire** [comment]
@TontonBa I dont think its ULX.. I was looking at your issue on FTpje's github and its the exact same problem i have, but i deleted ULX and the problem persists.

**Comment by Nayruden** [comment]
Talking with the user, it's not an issue with ULX. Looks like FPtje may have pushed a fix for DarkRP a few days ago.

TotonBa's problem seems to be that DarkRP notifies ULX to make him a superadmin, but fails or later removes him from superadmin without notifying ULX of the removal.
