### ISSUE TITLE
Client (number) overflowed reliable channel.

### ISSUE THREAD

**Issue by JoshuaBouvier** [TeamUlysses/ulx#35]
### Steps to reproduce
Not sure if it can be reproduced.

### Expected behavior
People should be able to connect to the server, but they get kicked off after connection

### Actual behavior
The person is kicked with the following error
"[Sun 20/03/2016 19:46:54] (Connects/Disconnects) name (STEAMID) disconnected (Client 33 overflowed reliable channel.)"
The Client (number) is usually a random number

### Error(s) in server console, if any
Dropped Cpt.Bubbles from server (Client 34 overflowed reliable channel.)

### Error(s) in player's console, if any
Client sending to server with no netchannel!
SoundEmitter: removing map sound overrides [8 to remove, 0 to restore]
Client sending to server with no netchannel!

### Version
ULib v2.60
ULX v3.70

**Comment by Nayruden** [comment]
How is this related to ULX?

**Comment by bigdogmat** [comment]
This looks to be an issue of just having to many addons or having to many poorly optimized addons sending too much data to the user.

**Comment by JoshuaBouvier** [comment]
Ah, ive noticed my mistake, I meant to post this on the ULiB page. It is related to ULiB though, not the easy answer of 'its the addons'. Of it was that easy why is it only affecting members who are in elevated permission groups. Also to take note, sometimes if someone is set from one of the staff groups to 'user'. The problem goes away, though set back to a staff rank, they are having the error again.

From extensive research and from all the data I can possibly gather, it suggests the the latest ULiB update is the culprit. This error dates back to 2005, and in a few of the more recent posts, ULiB has been implied as responsible for the error.

**Comment by bigdogmat** [comment]
> Of it was that easy why is it only affecting members who are in elevated permission groups. Also to take note, sometimes if someone is set from one of the staff groups to 'user'. The problem goes away, though set back to a staff rank, they are having the error again.

Could be an addon checking their rank before sending data, and so it'd only effect higher ranked peope.

> From extensive research and from all the data I can possibly gather, it suggests the the latest ULiB update is the culprit.

The last ULib update was a month ago, how long ago did this start happening?

> This error dates back to 2005, and in a few of the more recent posts, ULiB has been implied as responsible for the error.

This error is caused by something sending way too much data to the client and so over flowing the data channel, this includes net messages and I believe network and dt vars. Just because you've seen reports of people saying it's caused by ULib doesn't mean it's a ULib error.
