### ISSUE TITLE
Removing a group breaks DarkRP (and possibly other gamemodes) for players in that group

### ISSUE THREAD

**Issue by Bo98** [TeamUlysses/ulx#41]
### Steps to reproduce
1. Create group
2. Add yourself to created group
3. Remove group
4. Do something in DarkRP (suicide, open F4 menu, wait for salary etc.)

### Expected behavior
ULX not touching the player's team and thus not breaking everything.

### Actual behavior
ULX sets the player's team to ID 1001:

https://github.com/TeamUlysses/ulx/blob/master/lua/ulx/xgui/server/sv_groups.lua#L234

This potentially breaks any existing `ply:Team()` checks in gamemodes as the player is now in an unexpected and, in some gamemodes, invalid state.

### Version
v3.70w

**Comment by SticklyMan** [comment]
Sorry for the wait on this. UTeam was designed a really long time ago and was meant only for gamemodes that didn't use teams (which sandbox-derived check was a good use for). I've excluded DarkRP from UTeam, and can easily exclude any other sandbox-derived gamemodes that utilize teams as they come in.
