### ISSUE TITLE
!Mute and other commands are saying muted but still says mute is not a valid command

### ISSUE THREAD

**Issue by GlitchkingFTL** [TeamUlysses/ulx#42]
### Steps to reproduce
1.
2.
3.

### Expected behavior
ok so it should say !mute and say Someone has muted player

### Actual behavior
it mutes the person but then at the top it says the command !Mute is not a valid command and this happens with every command 

### Version
Run "ulx version" in console and paste the result
3.61
![img](https://cloud.githubusercontent.com/assets/18268479/14256926/21525f1e-fa69-11e5-955b-eca587ad88e6.jpg)

**Comment by Nayruden** [comment]
That 'invalid command' message is not coming from ULX/ULib

**Comment by GlitchkingFTL** [comment]
how do I fix it?

**Comment by Nayruden** [comment]
First you'll have to figure out what addon is creating the message. You can
do that by disabling them one by one until you stop getting the message.

**Comment by GlitchkingFTL** [comment]
what next

**Comment by Nayruden** [comment]
Ask the author to fix it.

**Comment by GlitchkingFTL** [comment]
when I delete on ulx doesent work I deleted ulib and I type muted

**Comment by GlitchkingFTL** [comment]
and It didn't work

**Comment by Nayruden** [comment]
ULib is necessary for ULX to work. ULX is necessary for the mute command to
work

**Comment by GlitchkingFTL** [comment]
ok so what do I disable

**Comment by GlitchkingFTL** [comment]
I need help fixin it

**Comment by Nayruden** [comment]
This area is for bug reports. For help and support, please use our forums.
