### ISSUE TITLE
big problem

### ISSUE THREAD

**Issue by thescottgames** [TeamUlysses/ulx#43]
### Steps to reproduce
1.download ulx and ulib
2.put it in your server
3.restart and join

### Expected behavior
Tell us what should happen
well it should act as normal

### Actual behavior
Tell us what happens instead
well dark rp errors that weren't there then there is mass lua spam in console and you spawn in as a joining/connecting job and we spawn in a road 

### Error(s) in server console, if any
[ERROR] lua/includes/modules/notification.lua:255: attempt to call field 'Register' (a nil value)
  1. unknown - lua/includes/modules/notification.lua:255
   2. require - [C]:-1
    3. unknown - Startup:1

### Error(s) in player's console, if any

[ERROR] lua/includes/modules/notification.lua:138: attempt to call field 'Count' (a nil value)
  1. fn - lua/includes/modules/notification.lua:138
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

### Version
well i can't do it in the player console because of lua spam and if i put it in the server console it says unknown command

**Comment by thescottgames** [comment]
also i wiped my server files reinstalled 
if you want add me on skype therealscottgames

**Comment by fixator10** [comment]
Try to redownload server or just verify your server files.

**Comment by Nayruden** [comment]
Something is very wrong with your server, but it doesn't seem to be related to ULX or ULib. Feel free to reach back on Skype if you disagree.

**Comment by Nayruden** [comment]
User reports this was fixed via a server wipe and load.
