### ISSUE TITLE
Authorization Issues with Nextbot Players

### ISSUE THREAD

**Issue by BurgerLUA** [TeamUlysses/ulx#46]
### Steps to reproduce
1. Kick several bots using ulx kick
2. Slap a player (or run another command)
3. Try to kick a bot

### Expected behavior
No errors, notifications should display.

### Actual behavior
ULIB UnAuth Errors, notification isn't displayed, bots and players can't be kicked anymore

### Error(s) in server console, if any

[ERROR] addons/svn_ulx/lua/ulx/modules/uteam.lua:23: attempt to index a nil value
  1. fn - addons/svn_ulx/lua/ulx/modules/uteam.lua:23
   2. unknown - addons/svn_ulib/lua/ulib/shared/hook.lua:110
    3. Spawn - [C]:-1
     4. fn - addons/svn_newfakeplayer/lua/autorun/server/sv_nfp_ai.lua:684
      5. unknown - addons/svn_ulib/lua/ulib/shared/hook.lua:110

  1. query - [C]:-1
   2. makePlayerList - addons/svn_ulx/lua/ulx/log.lua:354
    3. unknown - addons/svn_ulx/lua/ulx/log.lua:471
     4. gsub - [C]:-1
      5. fancyLogAdmin - addons/svn_ulx/lua/ulx/log.lua:450
       6. call - addons/svn_ulx/lua/ulx/modules/sh/util.lua:66
        7. __fn - addons/svn_ulib/lua/ulib/shared/commands.lua:943
         8. unknown - addons/svn_ulib/lua/ulib/shared/commands.lua:1296
          9. Run - lua/includes/modules/concommand.lua:54
           10. unknown - addons/svn_ulib/lua/ulib/shared/commands.lua:1311
            11. unknown - lua/includes/modules/concommand.lua:54

addons/svn_ulx/lua/ulx/log.lua:354: [ULIB] Unauthed playerBurger: !slap burger
addons/svn_ulx/lua/ulx/log.lua:354: [ULIB] Unauthed playerBurger: !kick furry
addons/svn_ulx/lua/ulx/log.lua:354: [ULIB] Unauthed playerBurger: !kick burger

### Error(s) in player's console, if any
None

### Version
ULib v2.60d (04/30/16)
ULX v3.70d (03/20/16)

**Comment by Nayruden** [comment]
Can you link us to the particular NextBots you are using?

**Comment by Nayruden** [comment]
Have not heard back from user, unable to replicate using instructions given, NextBots authenticate fine.

**Comment by SticklyMan** [comment]
Oops, that commit is supposed to fix issue 45. :P
