### ISSUE TITLE
Can't spawn admin weapons, even though I have every permission.

### ISSUE THREAD

**Issue by GamesArsenal96** [TeamUlysses/ulx#47]
Hello TeamUlysses,

I have been trying to setup a GMod lua testing server and I cant spawn administrative weapons even though I have all permissions. There are no errors. What is wrong and how can I fix it?

![gm_flatgrass0008](https://cloud.githubusercontent.com/assets/8171935/15532748/09cd77e4-2227-11e6-8746-d73920372db2.jpg)

**Comment by Nayruden** [comment]
ULX does not decide who can or cannot spawn weapons. Some weapons are "admin-only", which just means that the ULX group you're in needs to inherit from "admin" at some point.
