### ISSUE TITLE
ULX text missing

### ISSUE THREAD

**Issue by evilbiggy38** [TeamUlysses/ulx#48]
### Steps to reproduce
1. No clue
2. Go camping for a weekend, I guess?
3. Get a million steam messages complaining about it?

### Expected behavior
I should be able to go into ulx and be able to see what I'm typing in a ban message or the sort

### Actual behavior
Text box shows up, but not the text.  I can type in it, but I can't see what I'm actually typing

### Error(s) in server console, if any
None, I just fixed all the ones that could have been relevant
### Error(s) in player's console, if any
None
### Version
] ulx version
Invalid command entered. If you need help, please type "ulx help" in your console.

I am using the ULX off of the steam workshop

**Comment by Nayruden** [comment]
Listen server or dedicated?

If dedicated, please link me to the Workshop collection you are using for your server.

**Comment by evilbiggy38** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=661768521

I use nutscript 1.0, and the text in there is also broken.  I'm trying to see what on earth is wrong with it.

**Comment by SticklyMan** [comment]
Are you (or any of your addons) forcing a custom Derma/GWEN skin or theme?

**Comment by evilbiggy38** [comment]
I'm not sure... the issue popped up during April (there was an update that read "Fonts contained within Workshop addons are now properly loaded") 

I don't recall adding anything around that time that might have done it.

**Comment by evilbiggy38** [comment]
Although now that you mention it, in ulx settings I can only select the default derma skin

**Comment by evilbiggy38** [comment]
Found the issue.  Was in nutscript.

**Comment by Nayruden** [comment]
Can you share the details?
