### ISSUE TITLE
Add Option to Log ULX into Native Server Logs

### ISSUE THREAD

**Issue by Hazbelll** [TeamUlysses/ulx#5]
Would it be possible to implement an option to ULX to save its logs to [Source's Native Log Files] (http://wiki.garrysmod.com/page/Global/ServerLog) in the `/logs/` directory instead of to text files in the `/data/` directory?

This can be useful to those who like to use Source's own logging system for their logs rather than having various addons save their own logs into different text files, keeping things consistent and tidy. Source's own logging system also captures events that can't normally be captured via logging systems through Lua, such as engine errors.

**Comment by Nayruden** [comment]
Most events are already logged there by ULX. Do you have a specific logging request?

**Comment by Hazbelll** [comment]
I'm asking if it would be possible to add an option to choose whether ULX saves its own logs into the `/data/` directory **or** only log into the Source Engine's own log files. Currently, to have ULX log into Source's logs, you must also let it save another copy of its logs into its own log files. If you disable logging to files in the `/data`/ directory, ULX will also cease to log into Source's own log files.

My apologies, I should've made that more specific.

**Comment by Nayruden** [comment]
Okay, I'm tracking. Why do you want this?

**Comment by Hazbelll** [comment]
Having the same logs saved across multiple logging systems is unnecessary and redundant. It only creates clutter, wastes disk space (albeit text files will only consume very little) and can cause confusion if say, one logging system contains important logs that another does not (for example, as you said: ULX logs most events to Source's own logs, but not **all**). The Source Engine's native logs also log important events that can't be done through Lua, such as engine errors (like the model precache stringtable overflowing).

To most, server logging is really only an afterthought, but to others like myself, it's nice to have control over what gets logged, where and where not. Personally, I like to have everything logged to Source's log files and not duplicated again into other log files in the `/data/` directory.
Others may like it the other way around, having their logs saved into a single third party logging system, or leave it up to individual addons to create their own logging systems.

At the end of the day, it's just nice for everyone to have finer-grain control, which as of now, ULX in terms of logging to files, is either all or nothing.

**Comment by Nayruden** [comment]
To be clear, what ULX doesn't log to the main Source log is because it's already there by the normal logging process. But, point taken. I'm going to run this by the team for their opinion.

**Comment by Hazbelll** [comment]
That's fair enough then, although other logging systems do tend to still fragment what gets logged. ULX doesn't though then, so it's not an issue, although my other points still stand, especially in terms of redundancy.

Thank you for taking it into consideration however. I look forward to hearing back from you.

**Comment by Nayruden** [comment]
We've decided against it. It makes the configuration one more line more complicated, when you are probably the only person who would make use of it. We have to draw the line somewhere in the balance of simplicity vs configurability. Since this proposal doesn't really add value for a server owner, it's not worth the complication.

My personal suggestion to you would be to add a task to your server (cron job, whatever) to delete the ULX data logs on a regular basis.
