### ISSUE TITLE
DarkRP Can't remove ranks from users that aren't on the Server

### ISSUE THREAD

**Issue by ICE2582** [TeamUlysses/ulx#50]
I seen a similar post about this issue but the OP didn't seem too intelligent.. So let's start from the beginning.

I updated DarkRp to the most recent version. I run a modified version of DarkRP (Don't tell FPtje!) so it's a bitch to update but I finally did it. (Btw I tested this with a unmodified version of Darkrp and had the same issues so no it's not my code that's fucking shit up) 
Soon after the update me and my staff realized there was a issue with removing offline players ranks. It would say they're demoted but as soon as they join they have their rank all the sudden. So today I finally got around to fixing it, first step I did was Stop the server, delete the data files and install a fresh copy of ULX and ULib. So I start the server and join with a few of my staff and somehow we ALL have our ranks. How is this possible? Hm. So I do it all again. Fresh copy, deleted data files, then started the server. This time no one joined, so I opened the data files and all of them were default ones. 0 users, default groups, and default everything. As soon as I join, Bam, all the data files change and I have my rank, along with the other 100000 players on my server. Where is this Data coming from???? So my next guess is FAdmin. Yes I have it on all my servers. Never had any issues with it the past two and a half years on all my DarkRp servers. So I disable it, delete the data files, install a fresh copy of ULX and ULib and join back. It's fixed! I can now remove users ranks successfully when they're offline. BUT players get this error every time they load into the server. (Only known issue)

*Error seems to be Client only on PlayerInitialSpawn*

```
[ERROR] addons/ulib/lua/ulib/shared/sh_ucl.lua:48: attempt to call method 'UniqueID' (a nil value)
  1. query - addons/ulib/lua/ulib/shared/sh_ucl.lua:48
   2. fn - addons/ulib/lua/ulib/shared/cami_ulib.lua:18
    3. Call - addons/ulib/lua/ulib/shared/hook.lua:110
     4. PlayerHasAccess - addons/ulib/lua/ulib/shared/cami_global.lua:370
      5. unknown - gamemodes/darkrp/gamemode/modules/fpp/pp/client/menu.lua:37

Timer Failed! [Simple][@gamemodes/darkrp/gamemode/modules/fpp/pp/client/menu.lua (line 45)]
```

Damn, I thought I was getting close.. So I open menu.lua 
http://pastebin.com/NX2NxZxf
Here are lines 36-45

Is this a possible issue with CAMI? I don't know anymore. 

I also ran lua_run print( Entity(1):UniqueID() )
and got this

```
> print( Entity(1):UniqueID() )...
4152672573"
```

Don't know if that helps. 

**Current Version:** Fresh Unmodified Copy from Github
ULib 2.61
ULX 3.71

**Comment by NLGBrian** [comment]
same problem to me... @FPtje fix it plisz darkrpgod ;3

**Comment by TekBob** [comment]
OMG SAME ISSUE HERE!!!! I send a ticket about a week ago.

**Comment by TekBob** [comment]
I'll try your method, hope it works dude :D

**Comment by TekBob** [comment]
Fuck sake dude, this issue needs to be fixed fast...

**Comment by TekBob** [comment]
The core issue is FAdmin.

**Comment by ICE2582** [comment]
You guys can remove users through Fadmin for now. It'll remove it on both sides.

**Comment by TekBob** [comment]
Can you add me on Steam, I might need your help.

steamcommunity.com/id/tasid Thx <3.

**Comment by NLGBrian** [comment]
since i updated ULX the probles are gone.

**Comment by Nayruden** [comment]
Fixed via https://github.com/TeamUlysses/ulib/commit/75f70ca1ce59d1fde7be14a6a0b0c6d2f2862b17. Anyone using the GitHub version, please verify this issue is fixed for you.
