### ISSUE TITLE
GUI Issues (No Errors)

### ISSUE THREAD

**Issue by theantihero** [TeamUlysses/ulx#52]
### Steps to reproduce
1. ulx menu

### Expected behavior
I should be able to see "Server Settings Module"

### Actual behavior
If you look in settings or groups or anything that has a value you need to input, is all blanked out.
Same for group modification, doesn't list any users or doesn't show any options. Can't see any options for Manage Permissions as well.

It works fine on an older version of ulx and ulib.

This isn't a really big issue since I can manually do it, but having the GUI makes life easy.

### Error(s) in server console, if any
No error
### Error(s) in player's console, if any
No error
### Version
Run "ulx version" in console and paste the result
ULib v2.61
ULX v3.71

**Comment by Nayruden** [comment]
Sounds like a permission problem. To verify, run "ulx resettodefaults" in server console, change maps, then add yourself as a superadmin.

**Comment by Nayruden** [comment]
No response in over two weeks, closing issue.
