### ISSUE TITLE
[ERROR] Assumption fail!   1. unknown - [C]:-1

### ISSUE THREAD

**Issue by omar1231** [TeamUlysses/ulx#53]
### Steps to reproduce
1.
2.
3.

### Expected behavior
Tell us what should happen
if i type ulx adduser mynamae superadmin i should be admin but .assumption fail

### Actual behavior
i typed, ulx adduser leoshiro superadmin, before i used to do that with no problem
but since i made myself ulx adduser leoshiro no access it has been buggy and dont want me to become admin, i tried re installing and everything i tried instead adding to workshop addon instead of manually extracting them i tried everything still, after i type ulx adduser every key i type it returns 
Tell us what happens instead

### Error(s) in server console, if any
[ERROR] Assumption fail!
  1. unknown - [C]:-1

### Error(s) in player's console, if any
you dont have access to that command, leoshiro, i tried both server console and gmod console

### Version
Run "ulx version" in console and paste the result
] ulx version
ULib v2.61
ULX v3.71

**Comment by omar1231** [comment]
fixed, i added the darkrpmodification which i have previously deleted, but now only my health shows, the salary and everything gone i guess its conflicting with ulx and ulib which is the only addons i have can someone tell me why i cannot open Q too? the props menu?

**Comment by Nayruden** [comment]
ULX has nothing to do with your health, salary, or your main menu or props menu.
