### ISSUE TITLE
Error When Enter A Vehicle

### ISSUE THREAD

**Issue by wilson02715** [TeamUlysses/ulx#54]
When I get in a vehicle or a chair

I should be able to switch my view

But it keep said consle error, and I can't switch my view

This is the consle say
[ULib] lua/entities/y_helicopter/cl_init.lua:31: attempt to call field 'CalcView' (a nil value)
  1. fn - lua/entities/y_helicopter/cl_init.lua:31
   2. unknown - lua/ulib/shared/hook.lua:110

Please help

**Comment by Nayruden** [comment]
This error is coming from "y_helicopter", which is not one of our projects.
