### ISSUE TITLE
[Bug] GUI does not seem to update at all on Linux

### ISSUE THREAD

**Issue by sammyt291** [TeamUlysses/ulx#56]
### Steps to reproduce
1. Open the ULX menu
2. Select the groups Tab
3. Manage Teams
4. Press create new
### Expected behavior

A new team with the default values to be created and displayed ready for editing.
### Actual behavior

Nothing, 
Im unsure if this is because its just not updating in the GUI or it it actually is not creating the teams.
### Extra Info

I believe the issue lays with the GUI not updating as I can remove adverts and I see the effect in-game, Although they are still shown in the GUI after iv just deleted them, they no longer run.

The same can be said for adding players to ranks, It works but the rank user list under the rank stays empty etc..
### Error(s) in server console, if any

None
### Error(s) in player's console, if any

None
### Version

ULib v2.61d (06/12/16)
ULX v3.71

UPDATE:
After some testing with my friends server I think I have found a reason for the issue,
With ULX v3.71 and ULib v2.61d on a Windows server, the GUI updates perfectly.
After seeing his running fine I took an exact copy of his SVNed folders and tried it on our Linux machine, the issue still occured and the GUI still does not update even though its a 1:1 clone of the windows server's ulx and ulib.

So this leads me to believe its a linux only bug, the root of which I still do not know.

Any help would be very much appreciated.
- Sam

**Comment by sammyt291** [comment]
UPDATE 1:
After some testing with my friends server I think I have found a reason for the issue,
With ULX v3.71 and ULib v2.61d on a Windows server, the GUI updates perfectly.
After seeing his running fine I took an exact copy of his SVNed folders and tried it on our Linux machine, the issue still occured and the GUI still does not update even though its a 1:1 clone of the windows servers ulx and ulib.

So this leads me to believe its a linux only bug, the root of which I still do not know.

Any help would be very much appreciated.
- Sam

**Comment by Nayruden** [comment]
Tested on Ubuntu with no issue. Are you still having this problem?

**Comment by sammyt291** [comment]
Yes, Iv tried the following:
- Removing ULX related folders from /data/
- Using the force reset concmd
- Tried multiple older version combos of ULX and ULib back to march 15
- Tested on a brand new server with no additional addons

**Comment by Nayruden** [comment]
What distribution of Linux?

Are you having any other odd problems on the server or with other addons in general?

**Comment by sammyt291** [comment]
We are running Ubuntu 15.04,
No other addons (Of which we have a lot) have had an issue at all so far.

**Comment by Nayruden** [comment]
I tested on Ubuntu 14.04, so I am at a loss as to what your issue could be. We haven't heard any other reports of this, either.

**Comment by sammyt291** [comment]
Im totally at a loss as well, iv tried everything to resolve it that I can think, and its been an issue for around 2 months or more for us now

**Comment by Nayruden** [comment]
I'm sorry @sammyt291, but I'm going to close this issue -- it seems that you are the only one affected, which indicates there's not much we could do to help anyways.
