### ISSUE TITLE
Bans do not automatically get removed

### ISSUE THREAD

**Issue by dan2735** [TeamUlysses/ulx#58]
### Steps to reproduce
1. Ban yourself
2. Wait for ban to expire
3. Reconnect to Server

### Expected behavior
Tell us what should happen
You ban someone, when ban expires, they get unbanned. 

### Actual behavior
Tell us what happens instead
You ban someone, when ban expires, "Time Left" goes from "1 Minute" to just being blank, removeid STEAMID does not fix, ulx unban fixes.

### Version

ULib v2.60d
ULX v3.70d

**Comment by Nayruden** [comment]
Unable to reproduce. Please try this with no other addons present on the server other than ULX/ULib.

**Comment by Nayruden** [comment]
No response from original author in two months, unable to replicate, and no similar issues reported by anyone else. Closing as invalid.

**Comment by LifeDreamer24** [comment]
Still happens on my side...
