### ISSUE TITLE
Server console error on unban

### ISSUE THREAD

**Issue by fruitwasp** [TeamUlysses/ulx#6]
```
[ERROR] addons/ulx/lua/ulx/xgui/server/sv_bans.lua:152: attempt to compare number with string

  1. unknown - addons/ulx/lua/ulx/xgui/server/sv_bans.lua:152

   2. sort - [C]:-1

    3. getSortTable - addons/ulx/lua/ulx/xgui/server/sv_bans.lua:152

     4. unknown - addons/ulx/lua/ulx/xgui/server/sv_bans.lua:193

      5. unknown - addons/ulx/lua/ulx/modules/xgui_server.lua:65

       6. unknown - lua/includes/modules/concommand.lua:54
```

Occured just after an admin tried to unban a player via the menu.

**Comment by Nayruden** [comment]
You're having the same error as a previously closed issue https://github.com/Nayruden/Ulysses/issues/517. I'm showing that issue was resolved in 22e8e79e4762c1614f3b7c91c55d3be3cfeb1c9b. Are you using the latest version from GitHub?

**Comment by Nayruden** [comment]
No response, assuming non-issue.

**Comment by fruitwasp** [comment]
Sorry for the late response. It's fixed, yeh.
