### ISSUE TITLE
No command works if nobody is on the server

### ISSUE THREAD

**Issue by markusmarkusz** [TeamUlysses/ulx#62]
### Steps to reproduce
1. Start a server or change the map
2. Use a command

### Expected behavior
The command should be executed.

### Actual behavior
Nothing. Only if a player connects to the server then commands are executable.
If I run a command before a player connects then nothing happens.
If a player connects then the command got executed instantly.

### Error(s) in server console, if any
No error.

### Error(s) in player's console, if any
No error.

### Version
Run "ulx version" in console and paste the result
ULib v2.61
ULX v3.71d (07/02/16)

I think this error only occurs if the gamemode is terrortown (TTT). But I'm not sure.

**Comment by Nayruden** [comment]
The server goes into a suspended state at the start when no one's connected, there's little we can do to workaround that fact.

**Comment by bigdogmat** [comment]
If this is due to Think not running when no one's on the server, you can get around that using `sv_hibernate_think 1`

**Comment by Nayruden** [comment]
Oh, nice! I wasn't aware of that. Thanks, @bigdogmat.
