### ISSUE TITLE
XGUI does not show CAMI Privileges that was registered after XGUI initialize

### ISSUE THREAD

**Issue by roboderpy** [TeamUlysses/ulx#64]
EDIT: It does not show registered CAMI Privileges that was registered after XGUI is initialized
### Steps to reproduce

Register CAMI Privilege after XGUI is initialized
### Expected behavior
1. You are able to restrict access per group
2. Access appears in XGUI group configuration menu
### Actual behavior

Only first
### Error(s) in server console, if any

None
### Error(s) in player's console, if any

None
### Version

] ulx version
ULib v2.61d
ULX v3.71d
### Screenshots

![2016-07-20_15-03_garry s mod](https://cloud.githubusercontent.com/assets/6339511/16980717/97dbe106-4e91-11e6-9860-2abd0af6d633.jpg)
![2016-07-20_15-47_garry s mod](https://cloud.githubusercontent.com/assets/6339511/16980718/98191c10-4e91-11e6-88dd-0d0c116da5ee.jpg)
https://github.com/roboderpy/dpp/blob/master/lua/dpp/sh_access.lua#L29
### Suggestion about current menu

In the hover hint please display full Privilege name instead of just "A privilege from CAMI"
![2016-07-20_15-53_garry s mod](https://cloud.githubusercontent.com/assets/6339511/16980842/23c49ba4-4e92-11e6-89b5-96e120bc3d85.jpg)

**Comment by Nayruden** [comment]
@SticklyMan, do we need to make some kind of hook to notify XGUI when privileges change?

**Comment by SticklyMan** [comment]
@Nayruden The issue is likely here, which only happens on ulx.HOOK_ULXDONELOADING:
https://github.com/TeamUlysses/ulx/blob/master/lua/ulx/xgui/server/sv_groups.lua#L301-L309

Does UCLChanged get called when a privilege is changed? Otherwise, yeah, XGUI will need some kind of notification to repopulate and send out the updated accesses.

**Comment by Nayruden** [comment]
Got it; taking on the task of creating a hook for new privileges. @SticklyMan, you can implement it on your side (XGUI) before me; just tell me the hook name you choose.

**Comment by SticklyMan** [comment]
This should be resolved as of 3d393f5d96de351d4fcf088034a41e10c44b1816, along with ULib commits:
TeamUlysses/ulib@eda6abdccdef3094a2ee0dce8c824a24f1505f49
TeamUlysses/ulib@4926b5b9aac72d48a21086f281fadb1d5262dc5a

Please test and let me know if it's still not working as intended.
