### ISSUE TITLE
My garrys mod dedicated server is broken

### ISSUE THREAD

**Issue by DDplexityGaming** [TeamUlysses/ulx#65]
Hello, today i am having a problem with my props in Garrysmod its a dedicated server and i can't pick up props me or anyone else. I have falcon prop protection but i don't know if that's the full problem. If it is can somebody please help me resolve this issue as i want to have  a successful server for Garrysmod, All my physgun will do is just scatter on the props. One of my friends said it had something too do with limited phygun and how many times you can use the physgun if that is the case how may i fix this problem and where can i find phyguns options too fix this???

**Comment by UndercoverOrange** [comment]
what is your server IP? I doubt they will answer you sence this is not a ulx related problem so im going to help you out

**Comment by DDplexityGaming** [comment]
Don't worry about it man, i had to take the extra time to make a new
server. Thank you so much for trying to help me!😁
