### ISSUE TITLE
Random XGUI Error

### ISSUE THREAD

**Issue by MrUnknownGamer** [TeamUlysses/ulx#70]
For some reason, my alt is getting this error for no reason. I just had it join teh server and it gets the error every time. Can't open the !menu

```lua
[ERROR] addons/ulx/lua/ulx/modules/cl/xgui_client.lua:107: attempt to call field 'load_helpers' (a nil value)
  1. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:107
   2. Call - addons/ulib/lua/ulib/shared/hook.lua:110
    3. fn - addons/ulib/lua/ulib/cl_init.lua:49
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:110
```

**Comment by MaDmaxwell311** [comment]
What is the server console error showin? Also, look in your console when your server is loading, look at when ULib and ULX are loading.

**Comment by MrUnknownGamer** [comment]
I don't know. I logged on with my main account on the different computer, and it loads in just fine. I think it may be a problem with this one account, which seems to be my alt.

**Comment by uRandomAlex** [comment]
Try to remove GarrysMod/garrysmod/cache.

**Comment by MrUnknownGamer** [comment]
Will do when I get the chance.

**Comment by Nayruden** [comment]
Are you still getting this error?

**Comment by MrUnknownGamer** [comment]
Not anymore
