### ISSUE TITLE
Ulx won't work

### ISSUE THREAD

**Issue by Chewfeng** [TeamUlysses/ulx#73]
### Steps to reproduce
1. Sorry don't know how it happens
2. I Don't know how to fix it
3. I Tried deleting all of Ulx's contents and replacing it still didn't work
(I Got a good outcome when I remade the whole server but it takes hours)

### Expected behavior
Tell us what should happen
Able to use ULX Commands and options.
### Actual behavior
Tell us what happens instead
pretty much can't do anything from ulx menu or commands (well I can do some commands)
### Error(s) in server console, if any
None
### Error(s) in player's console, if any
None
### Version
Run "ulx version" in console and paste the result
ULib v2.61d
Ulx v3.71d

**Comment by Nayruden** [comment]
I have read this several times and I can't figure out what your problem is. Please be more clear as to what the problem is.

**Comment by Chewfeng** [comment]
I Have tried my best to update it but basically I just can't really do anything on ulx

**Comment by Nayruden** [comment]
I'm sorry but I can't make heads or tails of what your problem is.
