### ISSUE TITLE
Server is Lagging ( Spiking ) When someone joins the server

### ISSUE THREAD

**Issue by sayaloli1** [TeamUlysses/ulx#74]
### Steps to reproduce
1.i dont know how to fix it

### Expected behavior
the laggs should go away

### Actual behavior
hey, when someone joins my server my server is beginn lagging for some seconds ( like 5 - 10 seconds its spiking ) 

### Error(s) in server console, if any
no
### Error(s) in player's console, if any
no
### Version
ULib v2.61
ULX v3.71

**Comment by Nayruden** [comment]
Duplicate of #59.
