### ISSUE TITLE
The ULX Team Function Does Not work for me

### ISSUE THREAD

**Issue by Swiftking1013** [TeamUlysses/ulx#75]
Steps to reproduce
1. Open the ULX Menu
   2, Go click on a group
2. Manage Teams

Expected behavior

You are able to create and edit new teams.

Actual behavior

One of my old teams I have been trying to delete (named: Belch) will not delete no matter what. It cannot be edited and no other teams can be created.

Error(s) in server console, if any

This server is running ULX Admin Mod v3.71w by Team Ulysses from ulyssesmod.net

[ULX] lua/ulx/modules/uteam.lua:53: attempt to index local 'teamdata' (a nil value)
1. saveTeams - lua/ulx/modules/uteam.lua:53
   1. refreshTeams - lua/ulx/xgui/server/sv_groups.lua:194
   2. unknown - lua/ulx/xgui/server/sv_groups.lua:81
      1. unknown - lua/ulx/modules/xgui_server.lua:65
      2. unknown - lua/includes/modules/concommand.lua:54

P.S. I have already used "ulx resettodefaults FORCE" twice and same thing with uninstalling and reinstalling. This was my last resort.

**Comment by Nayruden** [comment]
If the team "Belch" keeps coming back after resetting ULX, it means that another addon (likely FAdmin) is creating it. We recommend disabling FAdmin; instructions can be found online. Let us know if this addresses the issue.

**Comment by FPtje** [comment]
FAdmin doesn't create teams. What the fuck are you on about?

**Comment by Nayruden** [comment]
Sorry, @FPtje is right. In initially reviewing the issue, I had assumed you had confused teams with groups (a common mistake in the gmod community). Can you please send me your groups.txt file from the ULib data directory? You'll find my email on the Ulysses website -- ulyssesmod.net

**Comment by Nayruden** [comment]
No response, closing issue.
