### ISSUE TITLE
Ulx logecho can be changed

### ISSUE THREAD

**Issue by iViscosity** [TeamUlysses/ulx#76]
### Steps to reproduce
1. Open console
2. Type 'ulx logecho #'
3. Profit

### Expected behavior
If the person has rights to change it, it should change.

### Actual behavior
Anyone can use it, whether a 'user' or any other elevated right without permission.

### Version
Run "ulx version" in console and paste the result
ULib v2.52d (02/06/16)
ULX v3.62d (01/30/16)

Just noticed versions are outdated, and I contacted the owners about it

**Comment by SticklyMan** [comment]
Works as expected in latest version, see below. (Tested in Gmod dev branch, sandbox, vanilla ulx/ulib only).  
Please double check your groups permissions, and ensure that access to the 'ulx logecho' cvar is configured correctly.  
Also try again after updating, see if that helps.  
Also note that entering a value that does not actually change the logecho value does not print the "You do not have access" message, as the value wasn't actually changed.  

```
] ulx logecho 1
] ulx logecho 0
] ulx logecho 1
] ulx removeuser sti
You removed all access rights from Yourself
] ulx logecho 4
You do not have access to this cvar (ulx_logecho), [ULX] Stickly Man!.
] ulx logecho 3
You do not have access to this cvar (ulx_logecho), [ULX] Stickly Man!.
] ulx logecho 2
You do not have access to this cvar (ulx_logecho), [ULX] Stickly Man!.
] ulx logecho 1
] ulx logecho 0
You do not have access to this cvar (ulx_logecho), [ULX] Stickly Man!.
```
