### ISSUE TITLE
[ERROR] lua/vgui/dtextentry.lua:301: attempt to call method 'IsEnabled' (a nil value)

### ISSUE THREAD

**Issue by iamgiygas** [TeamUlysses/ulx#77]
### Steps to reproduce
1. Update TTT from the one NFO installs (some 2015 version), to the latest 2016 version and the base gamemode using the github.
2. Update lua folder to the latest github version from the same github.
3. Open ULX, go to the settings tab.

### Expected behavior
No errors in console. Not sure what else is effected.

### Actual behavior
https://puu.sh/rzyYg/adaed2e81a.mp4
The error shows in both server console and player console.

### Error(s) in server console, if any
[ERROR] lua/vgui/dtextentry.lua:301: attempt to call method 'IsEnabled' (a nil value)
  1. GetDisabled - lua/vgui/dtextentry.lua:301
   2. SkinHook - lua/skins/default.lua:432
    3. unknown - lua/vgui/dtextentry.lua:249

### Error(s) in player's console, if any
[ERROR] lua/vgui/dtextentry.lua:301: attempt to call method 'IsEnabled' (a nil value)
  1. GetDisabled - lua/vgui/dtextentry.lua:301
   2. SkinHook - lua/skins/default.lua:432
    3. unknown - lua/vgui/dtextentry.lua:249

### Version
ULib v2.61d (09/04/16)
ULX v3.71d (09/05/16)

**Comment by iamgiygas** [comment]
Fixed? Reverted Lua folder in the gmod directory back to the old one and it works fine.

**Comment by SticklyMan** [comment]
Where did you update TTT from? TTT is included with gmod by default, so you shouldn't need to download or install anything extra. Needless to say, I just double checked ULX on the latest Garry's Mod dev branch with TTT, and it all seems to be working fine.

**Comment by iamgiygas** [comment]
The TTT update came from [Garry Newman's Garry's Mod github](https://github.com/garrynewman/garrysmod/tree/master/garrysmod/gamemodes/terrortown). The one that came with my installation of the Gmod servers was majorly outdated, 2015 to be exact, so I updated the TTT gamemode, base gamemode, and lua folder (inside the /garrysmod folder), and ULX broke. I returned the old lua files, and everything worked again, (except unbanning with Blastehh's SourceBans, which I'm trying to figure out, but it doesn't impact much). What I don't understand is that Gmod git is the newest, right? It seems like something in the updates broke everything. [The lua folder was updated 4 days ago](http://i.imgur.com/Yvx9sOj.png). One of the NFO staff that was helping me explained about how [rare](http://i.imgur.com/jKYOBij.png) server updates are, which means the gamemode becomes outdated, but the what about the rest? 

I did also start having problems with ULX/ULIB becoming outdated(?), even though the git on the managed panel was set properly, I guess it wasn't updating and I kept getting "Unauthed User" errors due to ULX and ULIB and then I noticed the gamemode spitting errors all over. For now, that issue seems to be fixed, until the next update or so. Whenever I fix it, it seems to only stay fixed for days or maybe a week, but I think now that I updated the gamemode, maybe that'll stop erroring, and everything that has ties to it will stop erroring.

**Comment by SticklyMan** [comment]
Yes, the terrortown files on that repo are kept up to date and sent out with every Garry's Mod update that is released. If you have a separate installation of TTT, it's likely overwriting the default Garry's Mod version to an older version. Here's the latest changelog (dev branch of gmod, not yet released to everyone) that does list some TTT changes:
https://wiki.garrysmod.com/changelist/

I did try switching to that branch for both my client and server, and everything seemed to work fine, even when running on a TTT map- this SHOULD mean that I was also running all of the latest TTT changes in the repo that you pulled.

There is likely something else at play causing your issues. You said you updated the base /garrysmod/lua folder as well? Keep in mind that a lot of those changes are potentially tied to other changes (to the server, clients, or the engine itself), and applying just the lua portion of the update is risky. Basically, you should try and always use the latest release version of Garry's Mod files, and wait for updates when they are released to everyone (usually once a month). If you DO want to test the latest Garry's Mod beta changes as seen on their GitHub page, there is a 'dev' branch of Gmod you can switch your client and server to, which you can easily find instructions online.

**Comment by iamgiygas** [comment]
Oh that makes sense. I know Gmod updates every once in a blue moon, but for some reason, the TTT gamemode was stuck on 2015, which may have been causing issues with ULX, since one module I use for ULX has controls for TTT cvars. The TTT installation I had was the one I had when I clicked "create server" on the managed panel for NFO and it installed the Gmod server on the VPS/VDS, it was not installed by me, but was retrieved from wherever NFO gets the files for installing a Gmod server. I have a feeling that since they use their own modified scripts for starting the server, with optimizations all around, they have a custom git or something that it pulls from, or some other source, and that source's TTT is outdated.
