### ISSUE TITLE
ULX Buggy

### ISSUE THREAD

**Issue by EzGunzBlazzinn** [TeamUlysses/ulx#78]
### Steps to reproduce
1.Demote a Player while Offline
2.Later they Join
3.No Longer Demoted

### Expected behavior
Tell us what should happen: They should be demoted for good if i demote them by steamID

### Actual behavior
Tell us what happens instead: When they log on by a later date or even the same day they somehow have their rank back. Example: Gunz Demotes SteamID from Admin to Mod -- later that day they get on with Admin rank instead of Mod.

### Version
Run "ulx version" in console and paste the result
ULib v2.61
ULX v3.71

**Comment by Nayruden** [comment]
Unable to reproduce; are you using FAdmin?

Log of my actions:
```
Client "Your dad" connected (10.211.55.3:27006).
status
hostname: Garry's Mod
version : 16.04.30/24 6533 secure
udp/ip  : 10.211.55.3:27015  
map     : gm_construct at: 0 x, 0 y, 0 z
players : 1 (8 max)

# userid name                uniqueid            connected ping loss state  adr
#      2 "Your dad"          STEAM_0:1:11444652  01:04       27    0 active 10.211.55.3:27006
ulx adduser dad superadmin
(Console) added Your dad to group superadmin
ServerLog: [ULX] (Console) added Your dad to group superadmin
Dropped Your dad from server (Disconnect by user.)
ulx removeuserid STEAM_0:1:11444652
(Console) removed all access rights from Your dad
ServerLog: [ULX] (Console) removed all access rights from Your dad
Client "Your dad" connected (10.211.55.3:27006).
ulx who
ID Name                            Group
3  Your dad                        user
```

**Comment by EzGunzBlazzinn** [comment]
Yes. It happens randomly some players will come back the one I set using "ulx removeuserid ID" and some user will come back the previous rank

**Comment by Nayruden** [comment]
We generally recommend disabling FAdmin, as it has a history of instability. There's a shared interface between FAdmin and ULX, which allows FAdmin to re-add users that were deleted from ULX.
