### ISSUE TITLE
Invisible Frame at pos 0,0

### ISSUE THREAD

**Issue by habobababo** [TeamUlysses/ulx#79]
### Steps to reproduce
Just spawn
I got 4 buttons up there, and 2 are blocked
Without ULX i get no issues

It's somewhere in the xgui_client.lua or xgui_helper.lua
i already tested that

### Actual behavior
There is a invisible panel at 0,0 its ~100px wide

### Version
ULX v3.71 and ULib 2.61

**Comment by SticklyMan** [comment]
![xgui_panel](https://cloud.githubusercontent.com/assets/95759/19448967/18bae294-9461-11e6-9449-33065f0f9bdc.png)

I see no such panel in the top left corner. Try turning on sv_cheats 1, then running the vgui_drawtree command to see what's there.

Are you running any ULX addons that integrate with XGUI? When does this panel appear, right on load? Are you getting any script errors? How do you know for sure that the problem goes away when you disable ULX?

**Comment by habobababo** [comment]
At fist, thank you for your fast reply. 
You are right, there is nothing over the buttons with vgui_drawtree thats awkward. 
I cant explain it.
I just moved the buttons to the right corner.
Im sorry for that issue report.

now to your questions:
q: Are you running any ULX addons that integrate with XGUI? 
a: no
q: When does this panel appear, right on load?
a: if i try to press the button right after i spawn, i can only press the third at the last 1/4 of the button
q: you getting any script errors?
a: nope
q: How do you know for sure that the problem goes away when you disable ULX?
a: by delete ULX or remove xgui_client.lua or xgui_helper.lua -- not getting any errors at this

**Comment by SticklyMan** [comment]
Is it possible for you to send me your code you are using to create your gui? I would like to try it myself and make sure XGUI isn't conflicting with anything. Send it to sticklyman@ulyssesmod.net.

Also, with your drawtree, make sure you have 'Show Hidden' and 'Highlight Mouseover' enabled, can help to figure things out. One more question, what gamemode are you running?

**Comment by habobababo** [comment]
gamemode is sandbox

'Also, with your drawtree, make sure you have 'Show Hidden' and 'Highlight Mouseover' enabled'
i did that

I completely rewrote the buttons and used other hooks. problem is gone now, but i still don't know why.
if you still want the code, tell me. I will give you the old (as i was pretty new to coding) and the new version of it.

**Comment by SticklyMan** [comment]
Nah, it's fine. I did some more double checking and think everything is in order, so I can do more investigating if I hear more reports. Thanks for the info!
