### ISSUE TITLE
Function ulx.adduserid isn't working

### ISSUE THREAD

**Issue by captain1242** [TeamUlysses/ulx#80]
### Steps to reproduce
1. lua_run "ulx.adduserid(nil,'STEAM_0:0:65265978','owner')"

### Expected behavior
It should Rank me to the Rank Owner

### Actual behavior
Its not doing anything

### Error(s) in server console, if any
lua_run ulx.adduserid(nil,'STEAM_0:0:65265978','owner')
> ulx.adduserid(nil,'STEAM_0:0:65265978','owner')...
[ULX] lua/ulx/log.lua:476: bad argument #2 to 'format' (number expected, got stri
ng)
  1format - [C]:-1
2. unknown - lua/ulx/log.lua:476
3. gsub - [C]:-1
4. fancyLogAdmin - lua/ulx/log
.lua:450
5. adduserid - lua/ulx/modules/sh/user.lua:77
6. unknown - lua_run:1

### Version
Run "ULX Steam Version"

**Comment by Nayruden** [comment]
This area is for reporting bugs, not for development help and support. Secondly, we never intended for the ULX functions to be called directly; either use the console command or use the ULib functions.
