### ISSUE TITLE
Add an extra setting for MOTDs

### ISSUE THREAD

**Issue by sammyt291** [TeamUlysses/ulx#84]
Hello,

When disabling the ulx motd there are [4 options](http://bit.ly/2fsDSLq).

It would be good to have a second option for disabling it completely but remove the chat message that occurs when someone uses !motd or presses the button.

This is very handy for when we use other MOTDs with ULX.

All the best,
Sam.

**Comment by Nayruden** [comment]
I do not understand the utility in this. Are many people trying to use the
MOTD command while it is disabled?

**Comment by sammyt291** [comment]
Yes, as other motds also tend to use the !motd command

**Comment by sammyt291** [comment]
guess even just a convar to disable the chat message it outputs would work:
ulx_motdprint 1/0

if motd is disabled and that cvar is 0 then just silently fail on the !motd command,
if motd is disabled and that cvar is 1 then print the usual message.

**Comment by zpetty33** [comment]
conVar added.
ulx_motdDisabledMessage = 0 will give you what you want here.
