### ISSUE TITLE
Lua Error (clientside)

### ISSUE THREAD

**Issue by mcNuggets1** [TeamUlysses/ulx#85]
### Steps to reproduce
Unknown.

### Expected behavior
Not erroring.

### Actual behavior
Erroring

### Error(s) in server console, if any
None

### Error(s) in player's console, if any
[ERROR] lua/includes/init.lua:705: attempt to call global 'rcc' (a nil value)
  1. fn - lua/includes/init.lua:705
   2. unknown - addons/ulx/lua/ulib/shared/hook.lua:109

### Version
newest

**Comment by yupi2** [comment]
>addons/ulx/lua/ulib/shared/hook.lua
That doesn't seem right

What is your server's addon folder tree look like? You can find out with
`"tree ."` in a command prompt or shell (without the double-quotes).
Did you put the ulib addon in the ulx addon?

**Comment by mcNuggets1** [comment]
Oh sorry, mister.
I have put ulx and ulib in one addon.
That does not have any conflicts tho.

**Comment by bigdogmat** [comment]
That [file](https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/includes/init.lua) (lua/includes/init.lua) doesn't have over 125 lines. Try validating your gmod.

**Comment by mcNuggets1** [comment]
Oh well shit.
That is straight from the clientside_errors file from my servers.

That has to mean, players in mass modificate their gmod clients x_x.
