### ISSUE TITLE
Missing Textures on the Superadmin, admin, operator, and user.

### ISSUE THREAD

**Issue by lljsullins** [TeamUlysses/ulx#87]
### Expected behavior
Tell us what should happen
I should be able to see my rank on the left of my RP name.

### Actual behavior
Tell us what happens instead
 When I type in ooc I see a missing texture to the left of my name.

### Version
Run "ulx version" in console and paste the result
ULib v2.61w
ULX v3.71w

**Comment by SticklyMan** [comment]
This feature is not a part of ULX or ULib, so we cannot help you with your issue. It likely a part of DarkRP or an addon for it.
