### ISSUE TITLE
Voteban restriction (Option Permanent is always shown in Menu)

### ISSUE THREAD

**Issue by Jannik-R** [TeamUlysses/ulx#88]
### Steps to reproduce
1. User hast voteban restriction (in my case 2h)
2. Open !menu as user
3. Goto Voting/voteban
4. Select any Player

### Expected behavior
Ther should not be the Banlenth: Permanent.

### Actual behavior
Ther is the Banlenth: Permanent.

### Version
ULib v2.61d (10/27/16)
ULX v3.71d (12/03/16)

**Comment by zpetty33** [comment]
Unable to replicate. The time restrictions appear for me.
