### ISSUE TITLE
BIG PROBLEM

### ISSUE THREAD

**Issue by zackeek** [TeamUlysses/ulx#90]
### Steps to reproduce
1. Chat
2.
3.

### Expected behavior
Hello, i got a big problem with ulx, i cant chat, no thing shows up. when i remove ulx it works, and installing it again it dont work. i dunno why

I have updated it yes. and ran fastdl sync

**Comment by Nayruden** [comment]
Try removing ALL addons (legacy and workshop). Confirm your chat shows up.
Then, add ULib/ULX back in and see if chat does not show up.

If it shows up, you have another addon conflicting. If it doesn't, we'll
take some other steps.

**Comment by zackeek** [comment]
u think it can be my chat addon? cuz i can see ulx bring etc in  chat

**Comment by Nayruden** [comment]
Yes

**Comment by Nayruden** [comment]
No further input in over a week, assuming author found the cause.
