### ISSUE TITLE
Commands not displaying properly in chat

### ISSUE THREAD

**Issue by Eagle9er9er** [TeamUlysses/ulx#91]
### Steps to reproduce
1. Use certain commands like Clear decals/ragdolls/stopsounds
2.
3.

### Expected behavior
Chat should display ""PlayerName cleared decals"

### Actual behavior
"#A cleared decals"

### Error(s) in server console, if any
none

### Error(s) in player's console, if any
none

### Version
Run "ulx version" in console and paste the result
] ulx version
ULib v2.61d (10/26/16)
ULX v3.71

**Comment by markusmarkusz** [comment]
See #89 and https://github.com/TeamUlysses/ulx/commit/120cb2c3dd6fd0461ae4b7085fa798a75c22d6d1
