### ISSUE TITLE
Random Server Crashes TTT

### ISSUE THREAD

**Issue by DarkIceXD** [TeamUlysses/ulx#92]
### What happens:
My TTT Server crashes often when map is changed or Round is over.
It is a Linux Server.
There are no errors in the console.
I tried ULX SVN and Ulib SVN but as soon as i join the server my game crashes.

### Version
ULX 3.71
Ulib 2.61

**Comment by Nayruden** [comment]
What leads you to believe that ULX/ULib is the cause of this? You've given no indication in your post.

**Comment by DarkIceXD** [comment]
When i remove ULX/Ulib from the server it seems to work fine.

**Comment by Nayruden** [comment]
I suggest trying to pair back to only ULX and ULib on your server and no other addons to confirm that ULX/ULib are the cause.

There's always odd edge cases, but it's unlikely that ULX/ULib would cause a server crash... especially since Garry has protections against the Lua state getting out of hand.

**Comment by DarkIceXD** [comment]
I removed already all addons and it might be something related to Pointshop 2 but i cant really tell because the crashes are so random sometimes it takes 2 mins to crash sometimes 2 weeks.

**Comment by Nayruden** [comment]
Are you sure it's not something to do with your server in general? Have you tried reinstalling the server files?

**Comment by DarkIceXD** [comment]
Yes unfortunatly i did this several times! And it didnt help at all.

**Comment by glenlife** [comment]
Redo the entire server from scratch I say, even the core game files, everything!

**Comment by DarkIceXD** [comment]
I will try since it is a hoster. They have to do it because they was they are using symlinks.

**Comment by DarkIceXD** [comment]
*say

**Comment by DarkIceXD** [comment]
Ok a reinstall of the server worked thanks alot!

**Comment by SouthpawAnex** [comment]
Were ULX and ULIB the issue?
