### ISSUE TITLE
My ULX isn't working anymore

### ISSUE THREAD

**Issue by Silenced0** [TeamUlysses/ulx#95]
I changed a font or something like that in the settings for myself, and now I got script errors for that and now I can use the ulx menu. I have already re subscribed to it and ulib twice and It didn't do anything. I also redownloaded GMOD and it also didn't do anything.
These screenshots here show what it looks like now
http://steamcommunity.com/sharedfiles/filedetails/?id=884833809
http://steamcommunity.com/sharedfiles/filedetails/?id=884834168

**Comment by SticklyMan** [comment]
There are issues when changing to some Derma skins with XGUI, and I haven't been able to really look into it very much. To fix the issue, you will need to edit your CLIENTSIDE garrysmod/data/ulx/xgui_settings.txt file and either change the "skin" line to "Default", or just remove the xgui_settings.txt file entirely and rejoin your server.

If that doesn't work, here is a thread with more info that may be helpful:
https://forums.ulyssesmod.net/index.php/topic,9330.msg47696.html#msg47696

**Comment by Silenced0** [comment]
yes thank you I deleted xgui_settings.txt file and it fixed it
