### ISSUE TITLE
chat not working

### ISSUE THREAD

**Issue by brenden1010** [TeamUlysses/ulx#96]
### Steps to reproduce
1.no steps
2.
3.

when i have ulx on my server that chat doesn't work when someone types in chat no one can see it
### Version
Run "ulx version" in console and paste the result
ULib v2.63w
ULX v3.73w

**Comment by Nayruden** [comment]
This indicates that you have an addon that's overriding PlayerChat and returning a value, thereby overriding the chat. Generally, the most straightforward way to figure out what addon is causing it is to remove them all, then add them back in one by one.

**Comment by brenden1010** [comment]
i tested everything with just ulx chat does not work
