### ISSUE TITLE
motd not loading wix websites

### ISSUE THREAD

**Issue by brenden1010** [TeamUlysses/ulx#97]
### Steps to reproduce
1.make a temp wix website
2.put it in the url and 
3. preview it will not work

### Expected behavior
Tell us what should happen
it should load the website 

### Actual behavior
Tell us what happens instead
it does not load

### Error(s) in server console, if any
none
### Error(s) in player's console, if any
none
### Version
Run "ulx version" in console and paste the result
ULib v2.63w
ULX v3.73w

**Comment by uRandomAlex** [comment]
Can you give us a Wix website to reproduce the bug?

**Comment by Nayruden** [comment]
I am unable to change the internals of how the gmod browser works. Only certain features of the HTML spec works within the browser.
