### ISSUE TITLE
Lua error on kick

### ISSUE THREAD

**Issue by Pandabehr** [TeamUlysses/ulx#99]
### Steps to reproduce
1. Join game
2. type: !kick playername test
3. ??????
4. profit

### Expected behavior
kick the actual player

### Actual behavior
error in server console

### Error(s) in server console, if any
```ULib queue error: addons/ulib/lua/ulib/server/player.lua:159: attempt to index a string value with bad key ('IsValid' is not part of the string library)```

### Version
ULib v2.63d (03/21/17)
ULX v3.73d (03/21/17)

**Comment by Nayruden** [comment]
Unable to duplicate, not reported by anyone else, and I see no obvious way this error would occur given the trace. Recommend stripping out all addons except ULX/ULib, then adding them back one by one to see if there's a rogue addon that's messing with command callbacks.
